### ISSUE TITLE
Behave tests - autocomplete tests which click on the first item in a list fail with xvfb

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1017]
When running in a local environment behave will click the correct item, but in xvfb it will click the second item in the list.

See if adjusting screen dimensions will fix this.

**Comment by yuanzhou** [comment]
@kshefchek I'm not sure this can solve your problem or maybe it will create new failed behave tests. But so far phantomjs is the headless browser I used on Travis for Phenogrid. I tried xvfb but always got some failed behave tests that I didn't see the failure on local firefox. phantomjs maybe a good alternative. And it's already supported by Travis.

**Comment by kltm** [comment]
While phantomjs is a nice auxillary, especially during development, I don't think it's a replacement for running actual browsers in actual environments, especially when you want to look towards using more backends than firefox and chrome.

@kshefchek - you can do things like run xvfb locally to see what's up. As well, assuming this is a Jenkins issue, we could switch to https://wiki.jenkins-ci.org/display/JENKINS/Xvfb+Plugin. Could you give more context about what the exact issue is?

**Comment by kshefchek** [comment]
@kltm I'm getting this from looking at the logs when we get failures in travis, but I haven't ran xvfb locally to debug.  Running with phantomjs does fix the issue in travis.

**Comment by kltm** [comment]
Could you supply a link, log, or the error message(s) in context? I'm not sure what "this" is.

Also, to be (more than a little) pedantic, you have a workaround using a less functional method (phantomjs over an actual browser). Now, it could be an issue with xvfb or firefox, or system settings available with the public travis (which IIRC is a vanilla debian flavor, but I forget which), or something else. However, I think it's very much worth exploring whether this is a browser mechanics problem or some version-specific rendering quirk--both of which could have larger implications for webapp development.

**Comment by kshefchek** [comment]
We have a test here:
https://github.com/monarch-initiative/monarch-app/blob/704f8e/tests/behave/maui_autocomplete.feature#L34

When typing hyper-be, we autocomplete on two items.  When running locally the test selects the correct item based on the link text and the test passes.  In travis the test fails and provides an output log of the page title that was selected, which is the second one in the list:

https://travis-ci.org/monarch-initiative/monarch-app#L1165

At one point we had the exact same issue with the test above this (autocompleting on ZRS), but after a SciGraph update this gene is now consistently the second item in the autocomplete drop down.

**Comment by kltm** [comment]
@kshefchek quick question: using ZRS as the template, why the difference between these two?
https://github.com/monarch-initiative/monarch-app/blob/704f8e/tests/behave/maui_autocomplete.feature#L30
https://github.com/monarch-initiative/monarch-app/blob/704f8e/tests/behave/maui_autocomplete.feature#L38

**Comment by kltm** [comment]
@kshefchek the link you sent me for the log shows passing at that line. Is there supposed to be a different reference?

**Comment by kshefchek** [comment]
oops that wasn't build specific, here it is:
https://travis-ci.org/monarch-initiative/monarch-app/builds/86266856#L1162

**Comment by kshefchek** [comment]
To answer https://github.com/monarch-initiative/monarch-app/issues/1017#issuecomment-149365823, this was my attempt to single out items with duplicate labels (genes) by also looking at their category, in this case species.

**Comment by kltm** [comment]
Okay, so here is the context:

```
Given I go to page "/"                                                          # steps/selenium-basic.py:15 0.956s
   And I type "hyper-be" into the navbar search                                    # steps/selenium-autocomplete.py:30
   And I wait until "Hyper-beta-alaninemia" appears in the autocomplete            # steps/selenium-autocomplete.py:41
   And I click the autocomplete item "Hyper-beta-alaninemia"                       # steps/selenium-autocomplete.py:61
   Then the title should be "Monarch Disease: Hyper-beta-alaninemia (OMIM:237400)" # steps/selenium-basic.py:45
```

```
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "steps/selenium-basic.py", line 49, in step_impl
          assert context.browser.title == title
      AssertionError
      Captured stdout:
      Monarch Disease: Beta-Aminoisobutyric Acid, Urinary Excretion of (OMIM:210100)
      Monarch Disease: Hyper-beta-alaninemia (OMIM:237400)
```

It looks like, interestingly, that in spite of the fact that it is apparently clicking on the correct link, the page is goes to doesn't seem to have the correct title or no title at all (assertion error), yes? Can you shed any light on the two (apparent) page titles that are dumped to standard out?

**Comment by kshefchek** [comment]
The first line in stdout is the title behave is seeing, the second is the title we have passed to function to test for:

https://github.com/monarch-initiative/monarch-app/blob/2d174b47a226e9e3c24420d0f9dfdcdf9d53ea7c/tests/behave/steps/selenium-basic.py#L47

Behave is landing on a page with the title "Monarch Disease: Beta-Aminoisobutyric Acid, Urinary Excretion of (OMIM:210100)" my assumption is that it is clicking on the second item in the autocomplete, since this is the second item.

**Comment by kltm** [comment]
Clicking on the second item, in spite of the fact that the selenium API clearly is going for the correct element by text identification, and works locally. Hm. Okay, how's this idea: the screen is sooo compressed on the test server (or due to some version quirk, like FF version) that the elements overlap, with the second item on top, so the click it at the right location, but hitting the wrong element?

Okay, so I'm looking at the .travis.yml file now to see what's going on; are variables set in the before_script still in effect during script?

For giggles, I wanted to see what this looks like locally:

``` bash
DISPLAY=:99.0 /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 80x40x16 && DISPLAY=:99.0 TARGET=http://localhost:9900 behave && kill -9 `ps -A | grep Xvfb | cut -d " " -f 1`
```

For me, with an X server size of 80x40, I get a fail on a single autocomplete test, but not the one in question, which seems like it could mean that somehow the xserver is not being setup properly on travis. It might be worth experimenting with a manual setup versus their tutorial, or trying one of their other setup methods (http://docs.travis-ci.com/user/gui-and-headless-browsers/).

**Comment by DoctorBud** [comment]
I think Seth's explanation is likely.

I've been working around some of these issues in my PR and with autocomplete. Firefox is very strict about interpreting the 'visibility' of an element and the screen size matters. In tests/behave/environment.py, months ago I had installed this in the before_all function:

```
    context.browser.set_window_size(1400, 900)
```

Recently, I found that during the test run, something shrinks Firefox and causes fails in later tests. So I currently use the same modification in the before_scenario function:

```
def before_scenario(context, scenario):
    context.browser.set_window_size(1100, 800)
```

(It turns out that 1100x800 is sufficient).

Even having a too short window (e.g., 1100x500) will cause the maui_analyze tests to fail because selenium can't 'see' what is scrolled below the window bottom and therefore, cannot click it.

**Comment by DoctorBud** [comment]
I ended up needing to re-adjust the window size in `tests/behave/environment.py` in light of the new Analyze UI. One of the `maui_autocomplete.feature` test scenarios was failing because the `phen_vis_svg_group` SVG element was not visible to `xvfb`, Firefox or Selenium during the `behave` tests. So I increased the vertical size of the window. Here's the PR: https://github.com/monarch-initiative/monarch-app/pull/1289
