### ISSUE TITLE
Create succinct URLs for downloads

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1022]
Can we come up with a better URL strategy if someone wants to link to a downloaded data set?

Currently on a given Monarch page tab the URL looks like this for the TSV:

http://sirius.monarchinitiative.org:8080/solr/golr/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=100000&start=0&fl=subject,subject_taxon,relation,object,object_taxon,evidence,source,is_defined_by,qualifier&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&facet.method=enum&csv.encapsulator=&csv.separator=%09&csv.header=false&csv.mv.separator=%7C&fq=object_closure:%22DOID:14330%22&fq=subject_category:%22gene%22&fq=object_category:%22disease%22&facet.field=subject_taxon_closure_label&facet.field=object_taxon_closure_label&q=*:*

Since we can't link directly to the tab on this page (or at least if you can I don't know how):
http://beta.monarchinitiative.org/disease/DOID:14330
It would be helpful to have a URL for any given tab/dataset.

**Comment by jmcmurry** [comment]
The download part of this ticket is related to our overall identifier resolution strategy for external (eg. RRID) and internal (eg. Monarch pages) identifiers. It requires some coordination and strategy before we implement and make public.

The second part of this ticket (direct link to a tab on a page) is not obvious, but it is working. Just use the # character followed by tab name in lowercase. http://beta.monarchinitiative.org/disease/DOID:14330#variants 

Kent and I have discussed that it would be desirable to make the tab fragment show up in the URL when you click there so that it is more obvious, however this hasn't been a huge priority. I will break this into a separate ticket. https://github.com/monarch-initiative/monarch-app/issues/1023

**Comment by jmcmurry** [comment]
Also, @mellybelly, was this in response to any conversations with users, or just an observation?

**Comment by kltm** [comment]
Not a comment on value one way or another, but to give some context here: the main reason for that URL is that it is a transparent pass-back to functionality that Solr just happens to offer--making the download a functionality freebie. Making the downloads have a "nice" URL means that you need to have a "translation" at some point, which is one more bit of mechanism to create/maintain.

**Comment by mellybelly** [comment]
no just was needing it for an example. I do think it is useful to be able to cite a data download from Monarch, even if just a URL and a date stamp.

**Comment by kshefchek** [comment]
It wouldn't be terribly difficult to have some route, such as /downloads/{id}/{var}_associations.tsv , var being all, gene, phenotype, etc. that forwards the user to the correct solr tsv page.  Date and time stamp may be a little more difficult.  Moving to the wishlist if this isn't a high priority.

As an aside, @kltm is there any way to set the content-disposition so this generates a save-as dialog box instead of sending users to the solr server?

@jmcurry how does this relate to RRIDs (other than accepting it as a valid id?)

**Comment by cmungall** [comment]
On 18 Oct 2015, at 11:54, Kent Shefchek wrote:

> It wouldn't be terribly difficult to have some route, such as 
> /downloads/{id}/{var}_associations.tsv , var being all, gene, 
> phenotype, etc. that forwards the user to the correct solr tsv page.

+1

may as well as json too, although this will of course be flatter than 
jsons we may want to add at a later date

> Date and time stamp may be a little more difficult.  Moving to the 
> wishlist if this isn't a high priority.

You mean a separate wishlist ticket for versioned access? Agreed. But a 
simple route that stops people bookmarking solr URLs is both simple and 
desirable.

> As an aside, @kltm is there anyway to set the content-disposition so 
> this generates a save-as dialog box instead of sending users to the 
> solr server?

This would be under control if we set a route in monarch app

**Comment by kltm** [comment]
Yes, you end up wrapping away variables in a route that proxies to solr--not rocket science, but you have a new mechanism that will be maintained and extended over time as users want new functions (I want to choose columns!). It might be worth considering just using the manager as the URL generator as it already has a fair amount of mechanism built-in (see AmiGO's various downloads, although is it still exposing the URL in the end, that would be wrapped away by the proxy in the monarch case).

Regarding content disposition, last time I checked, all the browsers had slightly different quirks, but the majority could be compelled to do a save dialog by (IIRC) actually _not_ doing the right thing.

**Comment by kshefchek** [comment]
As a first pass I've added /downloads/{id}.format (tsv, json, csv).  This generates all associations (subject or object = id) for an id.   I'll work on adding a route to get a specific id-category association table.

http://beta.monarchinitiative.org/downloads/NCBIGene:6469.tsv

**Comment by kshefchek** [comment]
Added category specific associations, for example:
http://beta.monarchinitiative.org/downloads/NCBIGene:6469/association/disease.tsv

Need to clean up the file names, and possibly the route naming.  Otherwise I think we can close and break anything more complicated out into new tickets.

**Comment by kshefchek** [comment]
File names fixed, credit @DoctorBud , closing but please reopen if there are any issues.  

Let's break out any further functionality (versioning, timestamps, RRIDs) into a new ticket.

**Comment by kshefchek** [comment]
Note I'm not in love with the routing I've chosen for ID-category associations discussed above (https://github.com/monarch-initiative/monarch-app/issues/1022#issuecomment-149362301), any suggestions @jmcmurry?

**Comment by frdougal** [comment]
Is this something relevant to Monarch's research interests?

http://nar.oxfordjournals.org/content/early/2015/10/19/nar.gkv1024.full

Chuck
