### ISSUE TITLE
Broken example service link for annotation sufficiency service

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1068]
https://monarchinitiative.org/score/?annotation_profile={%22id%22%20:%20%22MONARCH:Example1%22,%22features%22%20:%20[{%22id%22:%22HP:0000505%22},{%22id%22:%22HP:0000479%22},{%22id%22:%22HP:0001010%22},{%22id%22:%22HP:0000044%22}]}

On production I get a "Sorry. Your page could not be found."
On beta I get a "Your connection is not private"...

**Comment by kshefchek** [comment]
On production: I believe this is the same issue as #1044 (fixed), but hard to test because
On beta: We don't have an ssl cert

Marking as blocked because I think this is fixed, but I'm not sure how to test.  Is there a way to mock an https connection on a browser without the right cert?  If I click "accept the risks" the page works.
