### ISSUE TITLE
URL for autocomplete

### ISSUE THREAD

**Issue by frdougal** [monarch-initiative/monarch-legacy#1120]
We need a URL for the autocomplete functionality.  In an earlier discussion with Chris and Nicole, I told them the autocomplete used the following URL: http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/parkin.json params={"limit":20,"category":["gene","Phenotype","disease"],"searchSynonyms":true}

They suggested I use an alternative URL: http://persei.monarchinitiative.org:8080/solr/monarchAutocomplete/select?q=*:*

I would like a URL that looks like this: http://server_name/autocomplete/:term

Where :term is the search string
And the response is something like:
[
   {
       "ID": "1234",
       "taxon": "Mouse",
       "label": "my label 1",
       "type": "gene",
   },
   {
       "ID": "2345",
       "taxon": "Human",
       "label": "my label 2",
       "type": "protein",
   },
   {
       "ID": "4567",
       "taxon": "Zebrafish",
       "label": "my label 3",
       "type": "gene",
   },
   {
       "ID": "5150",
       "taxon": "Mouse",
       "label": "my label 4"
       "type": "gene",
   }
]

**Comment by cmungall** [comment]
We have two autocomplete solutions
- SciGraph
- Solr, following the GOlr design patterns

Your first URL is querying a SciGraph instance. BTW, for SicGraph documentation, use /docs/, e.g. for this instance: http://geoffrey.crbs.ucsd.edu:9000/scigraph/docs/

The second instance is a Solr instance. You can consult generic Solr docs here, but for consuming this I would recommend using the bbop js APIs which are aware of the golr design patterns. I believe this is the place https://github.com/berkeleybop/bbop-widget-solr-autocomplete @kltm and @jnguyenx can confirm.

I believe we previously decided that the Solr instance was the one to use, as it is easier to return fields such as taxon in the results. However, it would be useful to revisit the requirements. In Noctua, we have found that rather than building a special-purpose taxon-aware autocomplete, it is simplest just to append the taxon onto the label, where that label would otherwise be ambiguous (e.g. genes).

Assuming for now that we are going the solr route, your next challenge is the fact that /monarchAutocomplete/ is not regularly loaded, and may not have been loaded with the actual genes that you need to perform your testing. @jnguyenx and I were looking into this. This may end up waiting until we reconstitute the servers at OHSU, and migrate away from Bamboo to a more transparent loading mechanism.

**Comment by kltm** [comment]
While the selectize code is fresh in the bbop-widget-solr-autocomplete, the use of the managers from the bbop side is stale (previous version). This is on the short-term update list.

**Comment by jmcmurry** [comment]
@cborromeo please summarize what, if anything is blocking this from being closed. Thanks

**Comment by kshefchek** [comment]
I believe @cborromeo is still waiting on a solr index specifically for autocomplete and search.  Theres some alignment with noctua and I think a ticket somewhere.
