### ISSUE TITLE
Test Dmel and Celegans data with owlsim

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1125]
We have new data loaded in stage, test this in owlsim

**Comment by kshefchek** [comment]
One idea is to use golr to get the phenotypes, that way we can use the monarch API to automate testing of any source(s).  To get the phenotypes we could
- Query out phenotypes using the source field, dependent on this working properly
- Query them out with filters/query strings, for example:
  "fq": "subject_category:\"phenotype\" OR object_category:\"phenotype\"",
  "q": "object:WBPhenotype\* OR subject:WBPhenotype*",

And then run each phenotype through owlsim.  It's a brute force approach but would work.

**Comment by kshefchek** [comment]
@cmungall is there a way to check if a phenotype is known by owlsim by using the REST API?  I've generated a list of ids that do not return results in owlsim using Monarch simsearch, but I'm assuming this method is incorrect since we may have phenotypes without disease or gene associations.
[flybase-ids.txt](https://github.com/monarch-initiative/monarch-app/files/69801/flybase-ids.txt)
[wormbase-ids.txt](https://github.com/monarch-initiative/monarch-app/files/69802/wormbase-ids.txt)

**Comment by kshefchek** [comment]
I think I misunderstood this ticket when it was created as writing a literal test, see now it was probably just a request for adding this to owlsim.  Closing as we have fly and worm data in owlsim.
