### ISSUE TITLE
Iphone 4,  problems homepage

### ISSUE THREAD

**Issue by iamkoehler** [monarch-initiative/monarch-legacy#1189]
not sure if this must be fixed or has already been adressed, but this is how the current homeage looks on my iphone 4

![image](https://cloud.githubusercontent.com/assets/5172897/13309894/0a12036a-db81-11e5-982b-791781d36a09.jpg)
![image](https://cloud.githubusercontent.com/assets/5172897/13309895/0a153efe-db81-11e5-9695-11da22e9a4cc.jpg)

**Comment by DoctorBud** [comment]
I have been gradually improving the behavior of Monarch on mobile devices, but I've also been told that it is low priority (it's high priority for me, because I like narrow windows and the same thing that works for iPhone4 lets me have narrow windows). I think this will gradually be fixed as we evolve the UI, but if there is a driving need (e.g., demoing Monarch on an iPhone 4), I know HOW to fix these issues (basically, messing around with CSS and the Bootstrap thresholds and trying to ensure that no horizontal scrolling is ever necessary).

So I'd classify this as a known issue, and one that is not currently as important as other features. Next time I improve the iPhone4 behavior, I'll add a note to this ticket.

BTW, the way that I test Monarch and any other app I develop is to use the iOS Simulator and view the website through Safari on the virtual iPhone. Works pretty well.

**Comment by iamkoehler** [comment]
ok thanks!

**Comment by yuanzhou** [comment]
Just wanted to mention that Phenogrid is not designed for mobile phone even if you can view other Monarch website components in iphone.
