### ISSUE TITLE
Literature/Citation tab

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#123]
I think all types of "pages" ought to have a literature tab.

Though many of the references might be pointed to on the other tabs, A collection of the publication links might be really useful to someone to see all at once.

I think we can introspect the object on the page to find all of the "publication_id" or "publication_ids" objects.

What would be really nice is a grid to show how the publications are relevant.  i.e., there would be a little icon representing if the publication describes a "disease" or a "model" or a "genotype" or a "phenotype" or "pathway" or whatever (presumably json object it comes from).  I imagine that some publication will be referenced from multiple types.

**Comment by cmungall** [comment]
+1

**Comment by mellybelly** [comment]
Love this!
Also note that we have as a deliverable to return people related to the models as "experts". So this functionality would get us partially there.

**Comment by nlwashington** [comment]
Most objects with associations have associated publication_id (or ...ids).  These are what should be used.

You ought to be able to use the literature services, like:
http://beta.neuinfo.org/services/resource_LiteratureService.html
to get the short citation, and possibly the abstract for hovering.

To show in a table
object (disease label, or whatever got you here), data type (gene, disease...), PMID, short author list (Washington et al - do 1-3 max, maybe all in hover), title, year.

**Comment by nlwashington** [comment]
This should get you most of what you need to construct the short citations for the PMIDs:
http://beta.neuinfo.org/services/v1/literature/pmid?pmid=22080565

**Comment by nlwashington** [comment]
moved to June milestone.

**Comment by nlwashington** [comment]
@sarahjkim , not sure if you are doing iterative calls, but it appears that you could do one big fat call like:  http://beta.neuinfo.org/services/v1/literature/pmid?pmid=22080565&pmid=22080566

**Comment by sarahjkim** [comment]
Oh okay. I haven't gotten to doing the calls yet. I've just been working on aggregating all the PMID IDs from the various associations. This aggregate call seems very helpful. Thanks.

To update you on my progress, this is what the literature tab looks like (I've been pushing to the literature-tab branch so that I don't break anything while I'm still working on it).

![screen shot 2014-05-21 at 11 57 19 am](https://cloud.githubusercontent.com/assets/4628853/3045142/d3f92c58-e119-11e3-89d7-5d3a46bb6586.png)

**Comment by sarahjkim** [comment]
@nlwashington I have a stupid embarrassing question to ask you. How can I get the literature call result in JSON rather than in XML? I got all the calls to work, but the information is not organized coherently because it is XML (and not being parsed correctly).

http://beta.neuinfo.org/services/v1/literature/pmid?pmid=22080565.json does not work.

![screen shot 2014-05-21 at 4 15 52 pm](https://cloud.githubusercontent.com/assets/4628853/3047974/38585aec-e13e-11e3-8fd8-8b8124e40834.png)

**Comment by nlwashington** [comment]
try http://beta.neuinfo.org/services/v1/literature/pmid.json?pmid=22080565

**Comment by sarahjkim** [comment]
Ahhh! Thank you so much! :D

**Comment by sarahjkim** [comment]
Finished literature tabs! Let me know if you'd like anything changed.

![screen shot 2014-05-22 at 12 04 46 am](https://cloud.githubusercontent.com/assets/4628853/3051018/c76dd78e-e184-11e3-8a32-73e277970786.png)
![screen shot 2014-05-22 at 12 26 00 am](https://cloud.githubusercontent.com/assets/4628853/3051020/ca93f4d4-e184-11e3-91af-76e853f5bad9.png)
![screen shot 2014-05-22 at 12 32 10 am](https://cloud.githubusercontent.com/assets/4628853/3051026/d047dd1e-e184-11e3-8ee9-0b78de671cae.png)
![screen shot 2014-05-22 at 12 37 37 am](https://cloud.githubusercontent.com/assets/4628853/3051027/d362ea2a-e184-11e3-9542-196e63c6fc92.png)

**Comment by cmungall** [comment]
Looks great!
