### ISSUE TITLE
fallback for when ontoquest is down.

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#127]
we need a fallback plan for when ontoquest services are down.

right now, we get an "oops" something went wrong error on the monarch page, which is better than nothing.

the use case today was that i tried to get to http://tartini.crbs.ucsd.edu/disease/OMIM_270400, but ontoquest threw a null-pointer exception error.  (not a 500 error).  we should be able to handle this kind of error and not totally die.  there is still a lot of the page that can be populated without ontoquest information.

one possibility is to fall back to the standard nif-vocab if the lamhdi one goes down.  another is to just skip over this.

somewhat, but not exactly, related to #90.

**Comment by nlwashington** [comment]
also, i've requested returning 500 errors:
https://support.crbs.ucsd.edu/browse/NIF-10225

**Comment by kltm** [comment]
Technically, that's the correct answer--if you're reduced to trying to figure out what the different types of errors could be, you could end up with an endless problem.

One way we've dealt with this in the past is to have essentially a whitelisted response structure: any response that does not conform to a specific code and structure is considered bad or damaged, with a limited number of error modes depending. To make something like this work though, you probably need to agent-ize the remote call handling instead of essentially having it inline.

**Comment by harryhoch** [comment]
Seems to me that this is one of those cases where the answer is both-and. Ontoquest should return a clean 500 instead of barfing on a null pointer exception. That said, Monarch-app should try to catch things that completely go off base...

What do you mean by "agent-ziing"?

**Comment by nlwashington** [comment]
Jing has now changed ontoquest to return valid xml, with an empty set.  at least it won't barf.
