### ISSUE TITLE
Modifications to site search results Ranking, Representation, and Filtering

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1317]
## Ranking
- [ ] rank results according to lexical distance: **Exact matches to complete must be ranked above exact matches to partial string.**
  - [ ] if lexically equivalent, then rank according to richness of available data (?) Not yet sure about this one.
- [ ] weight:
  label matches >> synonym matches >> description matches*
- [ ] handle punctuation sensibly #1282 
- [x] enable stemming and  wildcard endings (eg so that a search for Pax includes Pax6 https://github.com/monarch-initiative/monarch-app/issues/1313)
- [ ] consider listing orthologs consecutively (?) See[ spreadsheet w/ example ranked results for "fanconi"](https://docs.google.com/spreadsheets/d/1nChD9EtmNHkOfuKFve6Vm9_42T3qZ8oUQTFX7yRf0jA/edit#gid=0)

`*` Note that while description matches should be relevant in boosting a result for which there is _already_ a label/synonym match, in other cases (if there is no match in label or synonym) we should weight them as _low_ as possible. This is because descriptions often are (understandably) peppered with mentions of entities to which the searched term is (or once was thought to be) _related_, rather than just describing the entity of interest. That step of exploring entity associations is best done from the landing pages themselves.
## Representation
- [ ] show textual overlap between query term and matched text (bold and highlighting) in label, synonym, or description, as appropriate)

_\- [ ] consider listing results in structured blurbs rather than in table form (This is how search results are typically rendered, making the results list look appropriately less like data in and of themselves) [edit: this task is on hold for now as of 9/2016]_
## Filtering
- [ ] include basic facets for species and result type
- [ ] include COUNTS for these facets out of the superset of all matches (not of the first page of 50 results)
- [ ] include human taxon for disease results (we may eventually have animal diseases like hip displasia, but for now 'human' should be adequate)
- [ ] include taxon for phenotype results, not just gene results (eg, human, mammal, fly, worm, etc)

Each of these features requires both back end and front-end work. Some of these are more important than others. A basic design proposal below for discussion.
<img width="676" alt="screen shot 2016-07-26 at 12 36 17 pm" src="https://cloud.githubusercontent.com/assets/3658863/17152645/93d1f01e-532d-11e6-84c2-74e326bb2263.png">

**Comment by kltm** [comment]
I'd note that most of these would be covered pretty much out of the box by adopting the the GOlr patterns and working with the upstream. For context, some of the related issues on the other side of the fence:
https://github.com/berkeleybop/bbop-js/issues/16
https://github.com/geneontology/amigo/issues/102

**Comment by jmcmurry** [comment]
Thanks Seth

**Comment by jmcmurry** [comment]
This used to be a comment about dead ends; I realize it is better as a separate ticket. https://github.com/monarch-initiative/monarch-app/issues/1319

**Comment by cmungall** [comment]
+1 to all these ideas

**Comment by jmcmurry** [comment]
@harryhoch do you think that @cborromeo could tackle the representation items above first?

**Comment by harryhoch** [comment]
@jmcmurry, let's discuss. I thought much of this was only hold until golr was resolved.

**Comment by jmcmurry** [comment]
Now that golr is resolved, we can start revisiting search results. Poking around, I think MGI and flybase has some nice patterns for us to consider if we go the table route, rather than the blob route for results. I like that they have two separate sections for "genome features" and "vocabulary terms". We have the multi-species problem to solve though so couldn't adopt their pattern outright. We might also consider having more categories of results.

**Comment by yuanzhou** [comment]
I looked at the main search and noticed that there are two behaviors. For instance, I type "p53" in the search box and the autocomplete will show a list of related items. 
- If I click one of the items, I'll be redirected to the target gene page.
- If I click the "Go" button instead of selecting from autocomplete list, I'll see all the search results (gene, diseases, phenotypes, and models) in a table view.

It seems @jmcmurry's design is only about the second search behavior as a better representation/organization of the table results. Am I correct on this?

**Comment by jmcmurry** [comment]
Correct, this whole ticket is just about site search (not autocomplete, though related). The most important things to fix on the UI side at this point are: 
- [ ] facets (on species, datatype).
  - [ ] Note that we will need some inference / closure as certain things may not be species-specific (eg. GO:0030330PHENOTYPE).  For now, because that backend may be missing esp w/r/t inference, it is fine to err on the side of inclusion rather than exclusion. Eg. if person facets on human, do include all disease results (even if we do not currently have the data to say with confidence that a disease is not a veterinary one).
- [ ] include a column where the label is shown (keep the matched text one)

**Comment by yuanzhou** [comment]
Just a quick update with my question. I installed the monarch-app 3 days ago and started poking around, the search looked as this:

![capture1](https://cloud.githubusercontent.com/assets/195873/19354150/c3995a50-9133-11e6-8e9d-1d69a149e99f.PNG)
The table was rendered based on the JSON structure:

![1](https://cloud.githubusercontent.com/assets/195873/19354326/47c1535a-9134-11e6-854a-3468dd82ff66.PNG)

This morning I pulled all the changes from master and the search result page changed a lot:

![capture2](https://cloud.githubusercontent.com/assets/195873/19354177/d9c0cc6e-9133-11e6-92a5-ee18ce98421c.PNG)

And the generated JSON structure is a lot simpler: 
![2](https://cloud.githubusercontent.com/assets/195873/19354348/5cd7ebd2-9134-11e6-80ce-4e305623711d.PNG)

Is this change as a result of the PR #1376? @kshefchek @jnguyenx

**Comment by jmcmurry** [comment]
yes, it is. A big step in the right direction, but we are still missing some results from the list, and we still have no way to facet/sort etc

**Comment by yuanzhou** [comment]
Just to update my progress. I redesigned the search results page based on the Isotope demo: http://isotope.metafizzy.co/

(Click the picture to view full size version)
![capture](https://cloud.githubusercontent.com/assets/195873/19495528/b720bcd8-9551-11e6-904b-d9645bbb3515.PNG)

I removed the repeated monarch logo from the heading.

Now we can filter the results by using these two combination filters. The filter buttons are parsed from the resulting JSON. And I also sorted the buttons in alphabetical and ascending order. 

At one point, I was thinking if I could take advantage of using different colors or icons to identify each result box/card. It may work for categories. But once we have many species, it's hard to apply those colors/icons. Any insights?

We also need to figure out a way of sorting/ranking the results. Now the results are just displayed based on their order in the resulting JSON in this masonry-like style.

**Comment by harryhoch** [comment]
Interesting, Zhou - thanks! I'm not sure what I think of it. It's very interesting , and uses space reasonably well. I agree that we might want to think about the rendering. 

Is this in a branch suitable for installing and trying it out? I'd like to give it a run...

**Comment by yuanzhou** [comment]
@harryhoch here is the branch of a working demo: https://github.com/monarch-initiative/monarch-app/tree/site-search-zhou

**Comment by harryhoch** [comment]
thanks, @yuanzhou. A few comments:
1.  In addition to the need for a rework of the rendering, would it be possible to (a) indicate the 
   total number of matches, and (b) add the number of matching items to each of the filter buttons?
2. How does "any" differ from "not specified"? we should probably not have both of these.
3. is it possible to make the selections into conjuncts, so that I might, for example, select human and mouse at the same time? 

I'm still not sure if I like the animation. It's cool, but..

**Comment by yuanzhou** [comment]
@harryhoch thanks for your suggestions. To answer your questions:
 1- (a) it's fairly simple to add the total number of matches. (b) adding the number of matching items to each button is also simple, but we may have to think about the combination use case. E.g., species button "Danio rerio(10)" indicates there are 10 results whose taxon is Danio rerio. And category button "gene(30)" indicates there are total 30 results whose category is gene. I'm not sure if it will cause any confusions if users click the "Danio rerio(10)" first then the "gene(30)", because the resulting number of matching items is more likely less than 10 due to the combination filtering.

 2- The "Not Specified" button only appears in species filtering. The reason is some results have missing "taxon". E.g., after I grouped all the results by their taxon, I could get this list:
![capture](https://cloud.githubusercontent.com/assets/195873/19519337/830b3c4c-95d9-11e6-9c60-785d012f30e2.PNG)

So I used "not specified" to indicate that some resulting items don't have "taxon".
![capture](https://cloud.githubusercontent.com/assets/195873/19519364/abf4e2e8-95d9-11e6-8ad8-71545d376b27.PNG)

There might be a better term instead of just saying "Not Specified".

 3-  It's a good idea to make selections into conjuncts. Then we might also want to visually separate each category/species.

I'm with you about the animation, and I'm more concerned about finding a better way of presenting the results to users so can tell the filters are effective to distinguish the results.

**Comment by jnguyenx** [comment]
@yuanzhou I don't think that you're using the right service to retrieve the docs from a search.

You should uncomment that line: https://github.com/monarch-initiative/monarch-app/blob/site-search-zhou/lib/monarch/web/webapp.js#L1091
and delete this one:
https://github.com/monarch-initiative/monarch-app/blob/site-search-zhou/lib/monarch/web/webapp.js#L1088

This way you'll get the full solr response with faceting.

**Comment by yuanzhou** [comment]
@jnguyenx I actually tried that earlier but it didn't return results. For example, with the same search term "p53" I got this even thought the autocomplete returns some results.

![capture](https://cloud.githubusercontent.com/assets/195873/19531070/4abe2f40-9604-11e6-9491-0ced428f1cb4.PNG)

**Comment by jnguyenx** [comment]
Yeah I've put some fake values so you can see how to use the function.
In this case put null in the category field (instead of ["category",
"leaf"]), and you should get the same results.

**Comment by yuanzhou** [comment]
@jnguyenx I tried again with this line:

```
var results = engine.search(term, null, null, resultsCount, 1);
```

`search/p53` still has no result, but the `search/p53.json` has results.

**Comment by jnguyenx** [comment]
Actually this is better:
`var results = engine.search(term, null, [], resultsCount, 1);`

It returns documents, but the UI is not parsing the response accordingly, hence it displays that nothing is found. So the work is to adapt the UI to this new payload.

**Comment by yuanzhou** [comment]
I took a close look at @jnguyenx 's new api endpoint with the generated JSON (attached), and I noticed two issues:

## 1). the "highlighting" is grouped in its own JSON property other than part of the "docs"

![capture](https://cloud.githubusercontent.com/assets/195873/19569000/ee6ffa0c-96c1-11e6-8ba8-7fa7190b9cf1.PNG). 

This makes the rendering not that intuitive since the highlighting is using the actual NCBI gene ID as the key/index, while the docs uses number index.

![22](https://cloud.githubusercontent.com/assets/195873/19569062/368ce070-96c2-11e6-8ec6-13dc30f6ad88.PNG)

## 2). The "facet_counts" contains group different versions of group names with same count:

![33](https://cloud.githubusercontent.com/assets/195873/19569136/a1595af0-96c2-11e6-84f4-b7ca425e8cb8.PNG)

![44](https://cloud.githubusercontent.com/assets/195873/19569139/a2ce2e9c-96c2-11e6-9d43-6ab0d9bef7a1.PNG)

![444](https://cloud.githubusercontent.com/assets/195873/19569141/a46b112a-96c2-11e6-88f0-bcfdca56f355.PNG)

At this point, I think the old result (https://beta.monarchinitiative.org/search/p53.json) format is more easier to parse and I can also just generate those facet counts by using `underscore` package to manipulate the result array.

[p35.json.txt](https://github.com/monarch-initiative/monarch-app/files/542256/p35.json.txt)

**Comment by yuanzhou** [comment]
Another question is we are limiting the number of results in the search code to max 50 while the actual count could be lots more than that. For example, term "p53" returns 315 results without the hard coded limit. Does this mean the 50 returned results are more relevant to the search? We need to find a good way of deciding how many results to return and which ones should be returned if we indeed need a upper limit.

**Comment by jmcmurry** [comment]
We should be following standard practice, ie. returning (and displaying) the _counts_ for each relevant facet, while displaying a reasonable number of actual results with interactive results paging; 50 results per page is fine. As we proceed, we may need to revisit ranking to ensure the best hits are at the tippy top.

**Comment by jnguyenx** [comment]
Hey Zhou,
I fixed the taxon facets. Ignore the highlights for now as it'll require a bit more work on the golr-manager side.

**Comment by yuanzhou** [comment]
Thanks @jnguyenx, I did a git rebase and merged your changes to my branch. I'm parsing the JSON data and rendering them in UI, and I came across another issue. Below are two results from `p53` search but they don't share the same structure. There's no taxon info in the first result object. Is this an error?

```
{
          "iri": "http://purl.obolibrary.org/obo/GO_1901796PHENOTYPE",
          "iri_searchable": "http://purl.obolibrary.org/obo/GO_1901796PHENOTYPE",
          "id": "GO:1901796PHENOTYPE",
          "id_searchable": "GO:1901796PHENOTYPE",
          "label": [
            "regulation of signal transduction by p53 class mediator phenotype"
          ],
          "label_searchable": [
            "regulation of signal transduction by p53 class mediator phenotype"
          ],
          "synonym": [
            "Any phenotype involving regulation of signal transduction by p53 class mediator."
          ],
          "synonym_searchable": [
            "Any phenotype involving regulation of signal transduction by p53 class mediator."
          ],
          "category": [
            "Class",
            "Phenotype"
          ],
          "category_searchable": [
            "Class",
            "Phenotype"
          ],
          "equivalent_iri": [
            "_:2ba2dae81c6271f36a3be61e84786346"
          ],
          "equivalent_iri_searchable": [
            "_:2ba2dae81c6271f36a3be61e84786346"
          ],
          "equivalent_curie": [
            "_:2ba2dae81c6271f36a3be61e84786346"
          ],
          "equivalent_curie_searchable": [
            "_:2ba2dae81c6271f36a3be61e84786346"
          ],
          "leaf": false,
          "_version_": 1548752694958620700,
          "score": 12.782033
        },
        {
          "iri": "http://www.ncbi.nlm.nih.gov/gene/281542",
          "iri_searchable": "http://www.ncbi.nlm.nih.gov/gene/281542",
          "id": "NCBIGene:281542",
          "id_searchable": "NCBIGene:281542",
          "label": [
            "TP53"
          ],
          "label_searchable": [
            "TP53"
          ],
          "definition": [
            "tumor protein p53 (Li-Fraumeni syndrome)",
            "tumor protein 53",
            "p53 tumor suppressor phosphoprotein",
            "tumor suppressor p53",
            "TP43"
          ],
          "definition_searchable": [
            "tumor protein p53 (Li-Fraumeni syndrome)",
            "tumor protein 53",
            "p53 tumor suppressor phosphoprotein",
            "tumor suppressor p53",
            "TP43"
          ],
          "taxon": "NCBITaxon:9913",
          "taxon_searchable": "NCBITaxon:9913",
          "taxon_label": "Bos taurus",
          "taxon_label_searchable": "Bos taurus",
          "taxon_label_synonym": [
            "Bos bovis",
            "Bos Tauurus",
            "domestic cattle",
            "domestic cow",
            "bovine",
            "cow",
            "cattle",
            "Bos primigenius taurus"
          ],
          "taxon_label_synonym_searchable": [
            "Bos bovis",
            "Bos Tauurus",
            "domestic cattle",
            "domestic cow",
            "bovine",
            "cow",
            "cattle",
            "Bos primigenius taurus"
          ],
          "category": [
            "Class",
            "gene",
            "sequence feature"
          ],
          "category_searchable": [
            "Class",
            "gene",
            "sequence feature"
          ],
          "equivalent_iri": [
            "http://identifiers.org/ensembl/ENSBTAG00000001069"
          ],
          "equivalent_iri_searchable": [
            "http://identifiers.org/ensembl/ENSBTAG00000001069"
          ],
          "equivalent_curie": [
            "ENSEMBL:ENSBTAG00000001069"
          ],
          "equivalent_curie_searchable": [
            "ENSEMBL:ENSBTAG00000001069"
          ],
          "leaf": true,
          "_version_": 1548752656998072300,
          "score": 12.77898
        }
```

**Comment by yuanzhou** [comment]
@jnguyenx and it seems those results that don't have taxon info are all phenotypes and diseases.

**Comment by jnguyenx** [comment]
We don't have the information for these nodes, I added empty strings and
empty array when it happens. Thanks for catching that!

**Comment by jnguyenx** [comment]
Ah hold on a bit, solr does not seem to index the empty arrays for some
reason, let me look into that.

**Comment by jnguyenx** [comment]
So unfortunately Solr does not return fields with "empty" values. I didn't
find a way to force it. You'll have to check manually if the field taxon or
taxon_label is present.

Also instead of parsing the response json manually, you might consider
using this class:
https://github.com/berkeleybop/bbop-response-golr

It'll give you access to handy functions to retrieve fields, docs number,
etc... The highlighted function that I'm writing will be part of this
library.

**Comment by kltm** [comment]
As well, we are definitely interested in having bbop-response-golr behave as a general abstraction here, and will happily take PRs to support this.
In this case, the method get_doc_field (or similar) could be extended to give a default return if nothing was found, and/or use the default return to hint whether the value to return should be a list or not.

(Alternatively, there could be hinting gotten from the golr-conf for this, but that's probably a bit much here.)

**Comment by jmcmurry** [comment]
This has been a useful discussion but is starting to be hard to execute. I'm therefore closing this ticket and pulling the actionable bits to:
Back-end: https://github.com/monarch-initiative/monarch-app/issues/1383
Front-end: https://github.com/monarch-initiative/monarch-app/issues/1386
