### ISSUE TITLE
nested OMIM diseases & equivalent ids that don't seem to be equivalent concepts

### ISSUE THREAD

**Issue by larrybabb** [monarch-initiative/monarch-legacy#1372]
I notice that occassionally there are parent-child or "is a" relationships between two omim concepts. Can you explain when and why this may happen?  The OMIM concepts I am specifically referring to are gene-specific concepts and thus it does not make apparent sense to me how one could be a subset or child of another.

For example,
Jervell and Lange-Nielsen syndrome OMIM:220400 (called Jervell and Lange-Nielsen Syndrome 1 in OMIM)
is a parent of 
Jervell and Lange-Nielsen Syndrome 2 OMIM:612347

and 
Primary Pulmonary Hypertension OMIM:178600 (called Pulmonary Hypertension, Primary, 1 in OMIM)
is a parent of several other omim concepts like
Pulmonary Hypertension, Primary, 2 OMIM:615342,
Pulmonary Hypertension, Primary, 3 OMIM:615343,
etc..

I think having an equivalent mapping between a DOID and OMIM concept may be worth having a subsequent review before publishing. It seems that DOIDs are meant to be more representative of the disease group (or polygenic?) types of diseases whereas omim concepts are mostly mongenic.  I know that OMIM has begun adding PS prefixes to one of the existing OMIM ids in a group that is considered a phenotypic series (omim term).  I believe if you're algorithms happen to identify that one concept as a disease group then maybe it should use the PS version of the id and keep the original id as the more specific subclass of the disease.

Again, just some thoughts as emerge and geneinsight begin to try to map existing disease concepts from a "free style" form to monarch's ontological concept ids. 

Any guidance or understanding on how these specific concepts might be split out or modified to better represent the associations between these concepts? (assuming these may need correcting of course)
And, do you have a recommended approach that we can take now when selecting a given node when it seems that they are mapped to both a DOID and MIM id and it seems like the MIM concept should be a separate child concept on its own? We were planning on applying all mapped equivalent ids to our concepts in our repository from monarch's current version, but maybe it makes sense for us to pick the id of the concept that we feel will end up best representing the concept in the event we don't feel all are really equivalent.  what do you think?

Any guidance or foresight on resolution management would be appreciated.

**Comment by cmungall** [comment]
The short answer is that we were assigning high weight to assignments orphanet makes about whether an OMIM and Orphanet pairing is likely to be exact vs narrower-to-broader. It turns out this was a bad idea, because often Orphanet treats the first entry in the phenotypic series as being the broader concept.

If we take your example Orphanet:90647 'Jervell and Lange-Nielsen syndrome', we can see that Orphanet says this is an EXACT match to OMIM:220400 ! Jervell and Lange-Nielsen Syndrome 1, but a BTNT match (broad-to-narrow) match to OMIM:612347 ! Jervell and Lange-Nielsen Syndrome 2

In fact, the Orphanet class is really broader than _both_. The general issue is covered here: https://github.com/monarch-initiative/monarch-disease-ontology/issues/149

You can see why Orphanet does this in many cases - often the first entry in a phenotypic series is written _as if_ it were the broader concept. But it's not correct.

As a result of this, we're downweighting the Orphanet E-vs-BTNT assignments, as there are other issues with these.

There's a bit more to it, but the TL;DR is that this is much improved in the next release.

**Comment by cmungall** [comment]
Hi @larrybabb - I'm going to close this ticket, but the discussion will be carried on over on this ticket in the MonDO tracker

https://github.com/monarch-initiative/monarch-disease-ontology/issues/157

(apologies for any confusion, I tried moving the ticket with the github issue mover but it didnt seem to quite work)
