### ISSUE TITLE
Links in search are broken (the CURIE is being used as the URL)

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1404]
https://monarchinitiative.org/search/Erdheim-Chester%20Disease

makes URLs like
http://doid:4039

**Comment by TomConlin** [comment]
Full DOID IRIs  (`<http://purl.obolibrary.org/obo/doid_[0-9]*`) show up in :   

     flybase.nt:         2698  
     wormbase.nt:        5112  

     genereviews.nt:     666  
     gwascatalog.nt:     324  
     hpoa.nt:            191080  
     kegg.nt:            1062  
     omia.nt:            1735   
     udp.nt:             38  
     zfin.nt:            814  

lowercase curie prefix and colon  `doid:` instead of uppercase w/under-bar happen never.

for example in `genereviews.ttl`  we have  

    @prefix DOID: <http://purl.obolibrary.org/obo/DOID_> .

but the 'DOID:' prefix is _never_ used (in any ttl file).  
instead  we find  
 
    GeneReviews:NBK350554 a owl:Class ;
        rdfs:label "Tubulinopathies Overview" ;
        OIO:hasExactSynonym "tubulin-ov" ;
        rdfs:subClassOf OBO:DOID_4 .

Where the what would be the DOID curie is under_bared and used as the local identifier on an OBO curie instead.  I do not think there is anything inherently wrong with this approach.
other than including the unused  `@prefix DOID: ` statement. 

if it is not in the ingest in must be in the app.

    monarch-app $ grep  'DOID_' conf/monarch-prefixes.yaml
      http://purl.obolibrary.org/obo/DOID_ : DOID
    monarch-app $ grep  'DOID_' conf/monarch-context.yaml
      DOID: http://purl.obolibrary.org/obo/DOID_
    monarch-app $ grep  'DOID_' conf/monarch-context.jsonld
          "DOID" : "http://purl.obolibrary.org/obo/DOID_",
    monarch-app $ grep  'DOID_' lib/monarch/api.js
            DOID: "http://purl.obolibrary.org/obo/DOID_",

Not liking the multiple mapping in the output any better than I liked the same multiple mappings in the input.

We should talk about the input & output sharing the same mappings

**Comment by cmungall** [comment]
Thanks for checking

Looks like nothing to do with dipper, purely a software issue

**Comment by jmcmurry** [comment]
@TomConlin can you close if you think appropriate. I can not repeat this bug.

**Comment by TomConlin** [comment]
If I recall this was the front end not using curie_map.yaml
