### ISSUE TITLE
gene phenotype and disease associations

### ISSUE THREAD

**Issue by zhengj2007** [monarch-initiative/monarch-legacy#1462]
@mbrush On the monarch website, gene and phenotype associations contain several model organisms, such as mouse, worm, and fly. However, gene and disease associations are only applied to human. Besides, the gene-disease associations have qualifier 'direct' or 'inferred'. For inferred G2D associations, does it mean the G2D associations inferred from model organism gene and phenotype associations by applying phenotype similarity?

Thanks!

**Comment by mbrush** [comment]
Hi Jie.  You are correct that gene-disease associations are only reported for human genes.  Genes from other species dont bear a direct relationship to human diseases.  But non-human genotypes/strains that involve variation in some gene are related to human disease by an is_model_of relationship.  e.g. see https://monarchinitiative.org/disease/OMIM:219700#models - from this you could infer some relationship between the d rerio cftr gene and cystic fibrosis.

as for your questions about direct and inferred qualifiers, as far as I know these should not be appearing on the web site any longer.  if you encounter them, please provide a link to where you see them.  I believe we discussed the meaning of these qualifiers in an e-mail exchange a couple months back (around 5/19). briefly here, 'inferred' does not indicate inference from phenotype similarity, but rather that, for example, a g2p association is inferred from an asserted association between a variant in that gene and the phenotype, or between the gene and a disease that is characterized by the phenotype. 

let me know if this or the answers i provided in my earlier emails are clear.  i will try to find the relevant text from this and copy it into this ticket as well.  and am happy to elaborate more if needed.

**Comment by mbrush** [comment]
relevant text from 5/19 email:
"Regarding the distinction between 'inferred' vs 'direct' associations . . . in the solr index a gene-disease association is tagged as 'inferred' when a data source asserts an association between a particular variant of the gene and a disease, and we infer an association between the disease and the gene affected by the variant. For example, the ClinVar  data asserts associations between specific genetic variants and diseases - and Monarch infers the gene affected by the variant to be associated with the disease. It is a trivial inference in this case - but we wanted to capture the fact that the source did not directly assert the gene-disease association.

Notably, we have since removed these 'inferred' and 'direct' qualifiers/tags from the data that is displayed in the web app and returned by our APIs - as it was confusing for users. Direct querying of the solr index is a rarely used route for accessing our data – and we still need to remove these qualifiers here."

**Comment by zhengj2007** [comment]
@mbrush Thanks a lot for your explanation. It is very useful and helpful.

**Comment by jmcmurry** [comment]
Great; I'll close this but feel free to re-open if you have any follow on issues.
