### ISSUE TITLE
Multiple genes appearing as comma-separated atom

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#151]
http://tartini.crbs.ucsd.edu/disease/OMIM_127750

Last entry is comma-separated, treated as single unit, links to:
http://tartini.crbs.ucsd.edu/gene/NCBI_gene:2629,%20NCBI_gene:6620,%20NCBI_gene:6622

I think we need lists in solr, but til then looks like we need to split (can we assume the ,-seprated IDs are in the same order as the ,-separated symbols)?

**Comment by nlwashington** [comment]
you'll notice in the code i recently committed that i've temporarily assigned the list of genes as a single entity instead of splitting it (with a big fat TODO to fix).  i forgot to fix before my commit.

i think you can assume that the source will have the ids and labels in the same order.  i will double-check that that is the case (and fix it in the view if it isn't the case).  if you would prefer the table to not have lists in the columns, i can change it.

i have also considered making a unified disease-gene table that will pull the annotations from multiple sources (like omim and clinvar, but then i could add in the gwas stuff too eventually), which i could make quickly.  let me know.

**Comment by nlwashington** [comment]
i believe this is fixed.  i see three rows, each with a single gene link.
