### ISSUE TITLE
Monarch's perspective on Pediatric Cancer and WHO's Cancer terms

### ISSUE THREAD

**Issue by larrybabb** [monarch-initiative/monarch-legacy#1567]
The ClinGen somatic focused groups have recently shown interest in the the classification of tumors being produced by the WHO as in this [article](https://www.ncbi.nlm.nih.gov/pubmed/27157931).  The particular table of interest from the article is [here](https://static-content.springer.com/image/art%3A10.1007%2Fs00401-016-1545-1/MediaObjects/401_2016_1545_Tab1a_HTML.gif).

If Monarch is aware and has any information on how this may be merged or associated with Monarch's ontology, it would be helpful to know.

Thanks.

**Comment by larrybabb** [comment]
related to this as well...
The somatic gene curation folks at ClinGen brought up the above terms in reference to a discussion related to the lack of "pediatric cancer" terminology, which they find is pretty important to their knowledge curation and tracking.  I can get more information if needed, but it would be great to know if the monarch folks (disease and/or phenotype) have any insights into developments related to providing more robust pediatric cancer terms.

Thanks again.

**Comment by balhoff** [comment]
I didn't look at them all, but the ones I checked (really only the first few) seem to be exactly represented in [NCIT](https://www.ebi.ac.uk/ols/ontologies/ncit). Some of those have the ICD-O code (the codes in the figure) in an annotation, but not all of them.

Maybe @mellybelly or @cmungall can comment on use of NCIT OBO Edition with MONDO.

**Comment by mellybelly** [comment]
@balhoff I think that the NCIT-OBO version could easily be used here. We can do some look to see if anything in that list is missing. I was also thinking we should revisit the ICD-O mapping and think about how to provide better tooling for conversion. We need to help people migrate from ICD-O, it is very out of date both content and technology-wise. This is something to discuss at the NCI semantics workshop too. @cmungall has been merging some portions of NCIT into MONDO as well, so that one can use HPO, MONDO, and NCIT together, but there is still work to be done there.

**Comment by cmungall** [comment]
@balhoff should we have the OBO version of NCIT translate NCIT_P334 to xref?

@larrybabb @mellybelly - yes the union should work seamlessly, but in the next mondo release we will include ICDOs propagated from NCIT

**Comment by balhoff** [comment]
> should we have the OBO version of NCIT translate NCIT_P334 to xref?

Maybe so; we could do that for several different value-specific properties (KEGG_ID, NCBI_Taxon_ID, USDA_ID, etc.)
