### ISSUE TITLE
fix/make universal footer

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#159]
All pages should have the same footer.  Right now the front page footer is different than the others.  All should be like the front page.

Also, please make footer text smaller.

Also, please make sure that the footer is always at the bottom of the page and/or bottom of the visual area/window.

**Comment by cmungall** [comment]
let's avoid repetitive code. Add this to the info object under info.includes

**Comment by sarahjkim** [comment]
The footer is actually universal with info.includes. The only footer different is the home page. This is because @harryhoch gave me a footer with abbreviations (#41), and @mellybelly stated that only the home page specifically should have the full names of the various organizations (#156). It is a simple fix to just choose one of the two, but I need to know which one I'm supposed to use.

Also, I can make the text smaller and put it on the bottom.

**Comment by mellybelly** [comment]
Thanks Sarah, please use the new one I suggested with the full names. Also the idea was to have the footer always show up at the bottom of the page, sometimes its higher up for some reason. 
Thx

**Comment by cmungall** [comment]
Thanks Sarah, I forgot we had the generic include
