### ISSUE TITLE
GDR mismatch

### ISSUE THREAD

**Issue by vgainullin** [monarch-initiative/monarch-legacy#1591]
This GDR appears to be a bad mapping
https://monarchinitiative.org/gene/HGNC%3A27172#diseases

How is the following link established? 
GAREM2 -> mitochondrial trifunctional protein deficiency | pathogenic_for_condition

**Comment by kshefchek** [comment]
This is inferred from one or more variant to disease associations, here is one: https://www.ncbi.nlm.nih.gov/clinvar/variation/194917/

My understanding is this snp occurs in both HADHA and GAREM2, as they overlap on opposite strands.  I believe this snp is more commonly associated with HADHA because it is located at a splice site, whereas it is an intronic variation in GAREM2.

I don't believe this is an error in our ingest, but rather we are not showing evidence adequately for a user to make this distinction, and we should also weight the association towards HADHA.

**Comment by vgainullin** [comment]
There is currently no disease in association with GAREM2, so this listing is misleading.

**Comment by kshefchek** [comment]
@vgainullin yes you are right, if there is not a gene to disease association we should not show one.  See https://github.com/monarch-initiative/dipper/issues/593 for the data ingest ticket, will use this ticket for addressing UI issues.  We likely still want to show that GAREM2 contains an intronic variant that is linked to this disease, but not make the gene to disease association directly since the gene is likely not affected by the variation. See GeneCards for GAREM2 as an example: https://www.genecards.org/cgi-bin/carddisp.pl?gene=GAREM2

**Comment by kshefchek** [comment]
We've removed the incorrect inference, see https://monarchinitiative.org/gene/HGNC:27172 , @vgainullin thanks for reporting!
