### ISSUE TITLE
Use consistent capitalization for categories

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/monarch-legacy#1638]
On this page: https://monarchinitiative.org/search/tremor there are different categories like 'disease', 'Phenotype', and 'gene'. It is distracting that Phenotype is capitalized.

**Comment by kshefchek** [comment]
I fixed this at some point and then reverted due to the hassle of having different cases on dev and prod - and biolink model now advocating for camel case.  This stems from us starting with camel case in scigraph for node labels/categories then switching to snake case halfway.

https://github.com/monarch-initiative/SciGraph-docker-monarch-data/commit/074327d74415da95f2b048fd294bfcbfe1b10132#diff-3a1e2768ecf8416d79597c7f7718e302
https://github.com/monarch-initiative/monarch-app/pull/1589

https://github.com/monarch-initiative/monarch-ui/pull/7
https://github.com/monarch-initiative/SciGraph-docker-monarch-data/commit/aa2286bf8b78de0535cc03e3312d46aa36c08820#diff-3a1e2768ecf8416d79597c7f7718e302

Plan is to normalize casing in the next release.

**Comment by monicacecilia** [comment]
Heyaaa, @kshefchek, I see this is now fixed this on beta. 
woohoo! 🎆

**Comment by kshefchek** [comment]
This has been fixed finally, thanks for reporting @balhoff
