### ISSUE TITLE
Consider citations tab

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#175]
I think that for any given page, we could collate the references in their own tab, where we can have some kind of typing that indicates what the citation is in reference to. For example, a disease-gene association might come from MGI, HPO team, etc., a disease might come from OMIM, a disease-pathway link from KEGG, etc. So sometimes the attribution is to a triple, other times simply to any given entity. 

By moving this info to its own tab, we could also take advantage of the NIF literature citations, and use full descriptive citations instead of PMID IDs. These could potentially be sortable by date, attribution source, type, or author.

@harryhoch @cmungall thoughts?
@nlwashington and I were discussing and really liked this idea.

**Comment by harryhoch** [comment]
this is quite reasonable.  I have been thinking about way to better link the info across tabs, but I haven't really gotten anywhere yet....

On Mar 10, 2014, at 3:48 PM, "Melissa Haendel" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think that for any given page, we could collate the references in their own tab, where we can have some kind of typing that indicates what the citation is in reference to. For example, a disease-gene association might come from MGI, HPO team, etc., a disease might come from OMIM, a disease-pathway link from KEGG, etc. So sometimes the attribution is to a triple, other times simply to any given entity.

By moving this info to its own tab, we could also take advantage of the NIF literature citations, and use full descriptive citations instead of PMID IDs. These could potentially be sortable by date, attribution source, type, or author.

@harryhochhttps://github.com/harryhoch @cmungallhttps://github.com/cmungall thoughts?
@nlwashingtonhttps://github.com/nlwashington and I were discussing and really liked this idea.

**Comment by mellybelly** [comment]
See also #162

**Comment by cmungall** [comment]
Great idea.

A simple tab with a reference list plus some indication of the context 
(e.g. "disease") should be easy

But recapitulating all the info from the other tabs flipped around to be 
centered around the reference is a little harder to do in a way that 
will be easily scalable and extendable to all pages.

**Comment by nlwashington** [comment]
Duplicates #123
