### ISSUE TITLE
make tabs more gracefully stack

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#200]
when you narrow the page, the tabs become floating boxes in two rows. It would be preferable if they stayed tabby, but stacked somehow.

**Comment by cmungall** [comment]
What's the default bootstrap behavior here? I feel we should stick with this as far as possible, as this is optimized across browsers, mobile platforms, etc

**Comment by sarahjkim** [comment]
@cmungall 
The tabs are not currently from Bootstrap. I tried out Bootstrap, but I disliked that it wasn't very responsive. Bootstrap has two types of tabs: (1) the regular tab and (2) "pills" (like the current boxes). The two types were not connected, so the tabs stacked very strangely (looked messed up).
So I decided to custom-make the tabs while borrowing ideas from Bootstrap. My version is more browser-size responsive because when the window becomes too small for tabs, the tabs turn into pills and break into layers. I thought this was more intuitive for mobile users as well.

@mellybelly 
I already tried multiple ways to keep the tabs while stacking them, but they all looked and felt horrible (in my opinion). That's why I chose to change to pills. Also, I think pills are more intuitive on mobile/tablets than tabs. If you can think of a way to stack the tabs while making it look alright, please let me know, and I'll change it to that way. At this point, though, every way I've tried to stack the tabs is less preferable to the pills view. Perhaps you'll have better ideas. :)

**Comment by mellybelly** [comment]
I think this looks good enough for now. Thanks Sarah.
