### ISSUE TITLE
If only one search result, don't show list of one

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#206]
Not sure if this is appropriate for Sarah to fix, but for example on this disease search:
Schwartz-Jampel Syndrome
there is only one result, but the search still takes you to a search results page. It would be better if we could just go the the one resulting page rather than the intermediate search page. With the categories in the autocomplete, we just don't need the intermediate page for one result.

**Comment by kshefchek** [comment]
Do we want this to just work off autocomplete; for example, if autocomplete returns one result send the user straight to that page.  Or should this include the search over NIF as well?

**Comment by nlwashington** [comment]
So the behavior of search right now is a bit odd.  The search performs two kinds of searches:
1.  autocomplete on ontology results
2.  general NIF search.

but this behavior is not apparent to the user.  they don't necessarily know that they _can_ get more results by hitting return than what shows up in the autocomplete.  is there a good way to make this more clear?  maybe a button would help?

nonetheless, i think a direct-to-page behavior should happen if:
1.  user _selects_ a specific term in the autocomplete list
2.  results of the search only find one match.  (less likely now with the fuzzy way the search is performed.)

**Comment by nlwashington** [comment]
@nathandunn, at the moment, the search sometimes times out because it's a heavy load on the NIF server.  is there an easy/conventient way we can perform/load the results of the search ajax-y that might offset the 502 errors that we sometimes get (which i think might be more to do with the size of the queries we perform)?

**Comment by selewis** [comment]
Seems I often get 502. I don't think it's unusual at this point.

**Comment by kshefchek** [comment]
I might able to work on this as well if @nathandunn can't get to it.  So the idea would be that the page would display the SciGraph search results at the top of the page, and below this we would asynchronously load the rest of the results.  Therefore if the NIF step fails we'll still have the SciGraph results displayed, and this will increase the speed of the page loading.

**Comment by nathandunn** [comment]
I’m trying to concentrate on the JBrowse / Apollo integration to display variation and human genome data, which is more in-line with my funding:  

 https://github.com/monarch-initiative/monarch-app/issues/585 https://github.com/monarch-initiative/monarch-app/issues/585

WRT to this feature, I had started on it editing the “search” route, but also kept running into 502 errors so often it was hard to work with effectively. 

That being said, it should be relatively simple . . if info.results + info.otherResults == 1, query the existing results and issue a redirect for that remaining issue.

Nathan

**Comment by nlwashington** [comment]
yes, @kshefchek it would be great if you can rely on it.  the plan sounds great.
we should send feedback to larry about the 502 error.  can someone look at the feedback on localhost to see where we are running into trouble?

also, make sure that if a person specifically selects an autocomplete item that they go straight to the relevant page without doing the search again.  this will help a lot too.

**Comment by kshefchek** [comment]
I've made two updates to the search functionality:
1. When a user selects an item in autocomplete the app takes the user to that page rather than to the search page.
2. The global search function is now running asynchronously, so page load speed has greatly improved.  See examples:
http://tartini.crbs.ucsd.edu/search/foo
http://tartini.crbs.ucsd.edu/search/food

It's worth noting we're still hitting NIF on the server side.  I just made a new page, /neurosearch/ that is called asynchronously when the /search/ page has finished loading.  I could also make this purely client side if needed and bypass the monarch app.

However, this leaves the issue of redirecting for a single result.  Since the NIF search results are now loading asynchronously, theres no way of getting a search count preemptively.  We could redirect if SciGraph only returns 1 result at the expense of not knowing what NIF will return.
