### ISSUE TITLE
Phenotype landing page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#211]
The phenotype landing page should have three things on it:
1. Phenotype spotlight. Can we color the spotlight banner something more exciting and same on all four page types? here is a suggestion for a phenotype spotlight:
1. A list of interesting phenotypes. Adding a few to the list that is already there:
   White forelock (human): http://tartini.crbs.ucsd.edu/phenotype/HP_0002211
   Scapular winging (human): http://tartini.crbs.ucsd.edu/phenotype/HP_0003691
   Abnormal physical strength (mouse): http://tartini.crbs.ucsd.edu/phenotype/MP_0004262

please remove the GABA synaptic transmission entry for now, we don't really deal with worm phenotypes adequately yet.
1. The analyze phenotypes tool. Can this be integrated on this page?

**Comment by cmungall** [comment]
Reopening for comments from Melissa:
- Should "renal agenesis" say (human)? Mice have kidneys. I think we want to avoid exposing architecture (e.g. that this database uses this kind of ID)
- Should we not deliberately push generic phenotypes that return multiple species to the top of the list? This is a highlight of what we are doing. E.g. rather than ceberellum development (which only has mouse annotations as a result of MGI curation practice rather than any biological reason) highlight http://tartini.crbs.ucsd.edu/phenotype/MP_0000849 morphology

**Comment by mellybelly** [comment]
Thanks Chris, I agree, no need to specify organisms in parentheses. Was following suit from what was there before but I agree its better not to have this (so Sarah please remove species in parentheses).

I also like http://tartini.crbs.ucsd.edu/phenotype/MP_0000849 abnormal cerebellum morphlogy. 
How about abnormal posture: http://tartini.crbs.ucsd.edu/phenotype/MP_0001504
for the same reason?

i do think that we are still showing too much underlying db structure though, and one issue is that the MP page and the HP page are not really merged. For example on the posturing page:

abnormal motor capabilities/coordination/movement
    abnormal posture = Abnormal posturing (HP_0002533)
        titubation
        hunched posture
        limp posture
        trunk curl
        abnormal limb posture
        abnormal resting posture

Will a user know what "Abnormal posturing (HP_0002533)" means and that it is a page with different data? it is even worse if the labels are the same.
thoughts?
