### ISSUE TITLE
gene page error

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#219]
this page threw a stacktrace:

http://tartini.crbs.ucsd.edu/gene/MGI:5476178

**Comment by kshefchek** [comment]
All of the gene pages on tartini are failing due to NIF issues.  This is what I see when I run it locally:

Status != 200. ExchangeObj source= ({connection:sun.net.www.protocol.http.HttpURLConnection:http://beta.neuinfo.org/services/v1/federation/data/nif-0000-03216-7.json?exportType=data...

You can see some gene pages on stage-monarch, but I don't believe it is in sync with the github repo.  For example:
http://stage-monarch.monarchinitiative.org/gene/MGI:5476178

This page isn't generating any data, as I haven't done extensive testing using IDs other than NCBIGene, but I'll go ahead and update the code to be able to hande MGI IDs.  Should I make sure any other IDs work as input, such as OMIM?

**Comment by kshefchek** [comment]
It looks like the website should work for some MGI Ids, for example:

http://stage-monarch.monarchinitiative.org/gene/MGI:98834
http://stage-monarch.monarchinitiative.org/gene/MGI:97490

MGI:5476178 isn't in our look up table, so this could be why we can't access it on the site:
http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-4?exportType:data&q="MGI:5476178"

**Comment by nlwashington** [comment]
first, @kshefchek we need to gracefully die, but also this is a real gene at mgi: http://www.informatics.jax.org/marker/MGI:5476178

http://monarchinitiative.org/gene/MGI:5476178

@nlw will investigate the data issues.

**Comment by nlwashington** [comment]
This gene id is found in the data:
http://beta.neuinfo.org/services/v1/federation/data/nif-0000-00096-6.json?q=MGI:5476178&exportType=data

**Comment by nlwashington** [comment]
Also found on the genotype table: http://beta.neuinfo.org/mynif/search.php?q=MGI:5476178&t=indexable&nif=nif-0000-00096-5&b=0&r=20

**Comment by kshefchek** [comment]
Agreed on having any errors die gracefully.  I think this issue should be fixed in beta.  However, tartini is currently failing at getAnnotationSufficiencyScoreFromAssociations() (http://owlsim.crbs.ucsd.edu/ is down).  This works if you run the app locally with the production configuration.

**Comment by kshefchek** [comment]
This appears to be resolved, closing issue.
