### ISSUE TITLE
Add images for sources in model table

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#228]
Right hand column in table:
http://tartini.crbs.ucsd.edu/disease/OMIM_270400

**Comment by sarahjkim** [comment]
I realized this is caused because the source is a string rather than an object. Once the source becomes an object with id and label, I just need to change line 701 in widgets.js from convChars to genSourceHref, and the images should display for sources.
![screen shot 2014-04-16 at 3 53 10 pm](https://cloud.githubusercontent.com/assets/4628853/2726394/0907b228-c5ba-11e3-9b91-d388c820e863.png)
