### ISSUE TITLE
linkouts to omim alleles broken

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#245]
E.g
http://127.0.0.1:8282/disease/OMIM_270400

in alleles tab

uses underscore, not dot

**Comment by kshefchek** [comment]
@cmungall would the idea here be to link to monarch pages using the dot notation and then redirect to OMIM (for now) using a percent sign instead of a dot?

For example: http://tartini.crbs.ucsd.edu/disease/OMIM_270400
Would we want the first allele to be:
http://tartini.crbs.ucsd.edu/variant/OMIM:602858.0003
but redirect to
http://omim.org/entry/602858#0003

**Comment by cmungall** [comment]
Yes, I think there would have to be something hacky

Ideally OMIM would make this resolvable
http://omim.org/entry/602858.0003

But we have to substitute the '#' ourselves

**Comment by kshefchek** [comment]
All right, I've implemented this but it is a little hacky, since the monarch URL is being stored in this format:
app.get('/variant/:id.:fmt?', function(request, id, fmt) {

I need to do something like this for the redirect code:
if (id.match(/^OMIM/)){
    url = makeExternalURL(id+"."+fmt);
} else {
    url = makeExternalURL(id);
}

But if that's okay, I'll go ahead and push the updated code.

**Comment by cmungall** [comment]
Go for it
