### ISSUE TITLE
Autocomplete weirdness with genes

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#276]
Go to http://tartini.crbs.ucsd.edu/

Type "IH".

You will see a list of genes, including "IHH"

Type an extra "H" giving you "IHH" in the search box

"IHH" disappears.

The service call is fine:
http://tartini.crbs.ucsd.edu/autocomplete/IHH.json

1 result, as expected.

This is something to do with search.js I think. Not sure if @kltm or @harryhoch worked on this? We'll be colated with @kltm for the hackathon tomorrow so can fix this then.

**Comment by harryhoch** [comment]
Chris, I haven't touched this code in quite some time. That said, I don't think it's necessarily about code that @kltm wrote.

As I see it, if I type "IHH", and I stay on the box, I see the "Search for diseases..." tooltip. 

If I then move the mouse out of the box, I see an IHH result as I should. 

The problem is a z-order collision going on between the "search-text-example" div, and  the jquery autocomplete div. 

partially fixed by https://github.com/monarch-initiative/monarch-app/commit/f45bfdd8b5e2ca28297bacec9ee4632828fb7076, which adds a z-index style for ui-autocomplete, but t now looks a bit funny when they are both shown. Can someone who's more of a CSS whiz than I am take a look at it?
