### ISSUE TITLE
missing disease on gene page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#281]
go to this page
http://monarchinitiative.org/gene/NCBIGene_6469
on the diseases tab, there is a row with cites that has no disease listed.
still problems with disease ontology as these are from orphanet?
or issues with getting disease-gene links? @nlwashington @kshefchek

**Comment by kshefchek** [comment]
The issue is with fetchDiseaseGeneAssociations() pulling data from the Orphanet NIF resource.  I'm having trouble tracking down why this is happening, but if I change:

} else if (resource.label == 'KEGG' || resource.label == 'ORPHANET') {
    if (r.omim_ids.split(",").length == 1) {

to:

} else if (resource.label == 'KEGG' || resource.label == 'ORPHANET') {
    if (r.omim_ids.split(",").length == 1 && r.omim_ids.split(",") != '') {

it removes this row from the output table.  Does this work for now or should we look for a better solution?
