### ISSUE TITLE
Change example search in search box

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#290]
from "Parkinsons" to "Parkinson's"
currently Parkinsons doesn't autocomplete so that isn't such a good example.

**Comment by pnrobinson** [comment]
I would be in favor of dropping the possesive form altogether (ie just Parkinson) etc as the primary name for all diseases with an eponym.
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson

---

Von: Melissa Haendel [notifications@github.com]
Gesendet: Samstag, 19. April 2014 07:06
An: monarch-initiative/monarch-app
Betreff: [monarch-app] Change example search in search box (#290)

from "Parkinsons" to "Parkinson's"
currently Parkinsons doesn't autocomplete so that isn't such a good example.
