### ISSUE TITLE
Tidy term info

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#3]
List of synonyms should be presented in a more structured way. Add synonym provenance (requires OQ to return this info).

The IDs should be split by database and hyperlinked.

**Comment by sarahjkim** [comment]
Synonyms and IDs still need to be split into separate strings rather than concatenated into one big string. They are running off the page and causing viewing problems.
![screen shot 2013-12-20 at 11 19 48 am](https://f.cloud.github.com/assets/4628853/1793086/d5f536c2-69ab-11e3-844c-ee51e829d0e5.png)
![screen shot 2013-12-20 at 11 20 56 am](https://f.cloud.github.com/assets/4628853/1793088/de4efd08-69ab-11e3-9436-a3ea1c1cd1bd.png)
