### ISSUE TITLE
Tour page needs images and descriptions

### ISSUE THREAD

**Issue by sarahjkim** [monarch-initiative/monarch-legacy#30]
I finished the skeleton for the tour page, so I am requesting descriptions and images/infographics. These are the sections which probably need information/images:
- Purpose: I just took the text from the Drupal site.
- Beta Release: There is nothing here at the moment except a sentence about contacting info@monarchiniative.org for future beta testers.
- Future Release: I thought having future models or something here would be cool. A description would be nice, too.

P.S. You can send high quality images to sarahkim@lbl.gov or place them in the images folder. Thanks!

![screen shot 2013-12-19 at 6 22 49 pm](https://f.cloud.github.com/assets/4628853/1788155/bed2f4e0-691d-11e3-8d6d-2d42cd99d829.png)
![screen shot 2013-12-19 at 6 22 52 pm](https://f.cloud.github.com/assets/4628853/1788156/bedc5be8-691d-11e3-93e1-8dbae44eca58.png)
![screen shot 2013-12-19 at 6 22 56 pm](https://f.cloud.github.com/assets/4628853/1788158/c1c5242a-691d-11e3-8128-844ff0825d5c.png)
![screen shot 2013-12-19 at 6 22 59 pm](https://f.cloud.github.com/assets/4628853/1788159/c1c5ce3e-691d-11e3-853b-ac5caaf178d7.png)

**Comment by sarahjkim** [comment]
Replaced by issue #58.

**Comment by mellybelly** [comment]
Sarah, I think on this tour page, we should relabel the top to something more like "About Monarch" since there really isn't a tour? At least not the way I think of it (others may feel differently).

Also, I think we can get rid of the FAQs for now, since they aren't so relevant and we probably don't have time to come up with good FAQs for this release.
