### ISSUE TITLE
Links to non-human genes not working

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#307]
http://monarchinitiative.org/gene/NCBIGene_10622

select Homologs
http://monarchinitiative.org/gene/NCBIGene:828101 (arabidopsis)
==> fail

**Comment by kshefchek** [comment]
I've played around with this a little bit but haven't pushed anything to beta.  The issue is that we're passing a null value into the quote function in the mapNCBIGeneToKO() function.

if (ncbiToKeggGene.results.length == 0 ) {
        kegg_geneid = null; 
}
This could be changed to
kegg_geneid = '';

But I need to check if this breaks anything.

Another solution is checking the argument v in the quote function:

if (v.match(/^[0-9]+$/) != null) {
        return v;
}
could be changed to
if (v != null && v.match(/^[0-9]+$/) != null) {
        return v;
}

**Comment by kshefchek** [comment]
Or alternatively, we could null check the variable before querying NIF, perhaps this is the best way to go about it, for example:

if (kegg_geneid != null){
        var keggGeneToKO = this.fetchDataFromResource(null,kegg_ko_map_resource_id, keggtr, null,["gene_id:"+quote_kegg_gene],null,null,{useClosure : false});
        return keggGeneToKO.results;
} else {
        return [];
}
