### ISSUE TITLE
profile search grid view empty when no species selected

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#312]
E.g.

http://tartini.crbs.ucsd.edu/analyze/phenotypes/?input_items=MP_0002639+MP_0004704+MP_0002135+HP_0000133+MP_0000548+HP_0001518&limit=100&target_species=

**Comment by frdougal** [comment]
I'll dig into this.  I'm seeing the following in firebug:
modeltype.js line 333
TypeError: tempdata[0] is undefined 
self.options.targetSpeciesName = tempdata[0].name;

**Comment by mellybelly** [comment]
@cborromeo can you address or reassign asap? 
@BeckyBoes can perhaps help

**Comment by nlwashington** [comment]
this now works, but while the table does the right thing (all species), the phenogrid defaults to mouse.   when @BeckyBoes adds the flag for "all" to the phenogrid, we should be able to accomodate this.  i will leave this open until "all" on the phenogrid as an option is resolved.

**Comment by harryhoch** [comment]
Should we talk about thebehavior for "all"? I'm concerned that if "all" includes human diseases when we have inputs of human phenotypes, the non-human data will be swamped by higher similarity to human models. Is this a concern? If so, how should we handle it? Should it be "all model organisms"?

**Comment by nlwashington** [comment]
well, this is def a concern, particularly as we are limiting the results to just the top 100 in the grid.  but, the problem is that the way the owlsim service call works is somewhat hacky in that either you have to specify an identifier prefix or none at all...there's no way to specify a set (to say perform a union), or to specify some other attribute of the data (for example, by taxon or target type).  currently, specification of a taxon id by the phenogrid is transformed and mapped to just an identifier prefix.  this is not an ideal solution, and @cmungall will have to comment on how we can change this going forward.  therefore, the only way we could do the "all models" or "non-human" call today would be to either:
1.  iteratively call each non-human species, and then create a ranked list of the union of the results ourselves OR
2.  do the general call for everything, and remove all the human results.  

neither are ideal.  what do you suggest?

**Comment by cmungall** [comment]
Note that if you come in from a phenotype profile from a mouse gene page, then mouse results will swamp the others, so the all-bar-human-diseases approach seems imperfect.

Once we fix #243 we could just have a default species and let the user decide.

Either way we should have better pre-filtering of target lists on the owlsim end; we'll load type (gene vs genotype vs disease) and taxon. We could then in principle allow any boolean combination of these properties

**Comment by harryhoch** [comment]
How about "all but x"? where x would be the starting context (human, mouse,etc.) that began the query?

**Comment by boesb** [comment]
Fixed:  Default View is "Overview",
