### ISSUE TITLE
hover on model viewer should display subsumed phenotype

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#317]
The left column shows the query phenotypes, the right one the subsumers, so the hover over the squares should show the model's subsumed phenotype. Currently it shows the same subsuming phenotype as on the right.

(I know we talked about this amongst many other improvement ideas but this one is high priority, apologies if other ticket exists)

**Comment by harryhoch** [comment]
@mellybelly, let me see if I can clarify. Do you mean to say that instead of the uberpheno-ish term on the right that you want to see the specific term that is asserted to match the model in the column? 

If so, I agree, but I'm not sure that we get that data out of the services at the moment...

**Comment by frdougal** [comment]
I agree with Harry.  I think Nicole needs to add some data to the similarity call.

**Comment by mellybelly** [comment]
@nlwashington I figured that it might be the case that you didn't yet have the data - also the data is originally calculated to the genotype not the gene. It is really important that we have this thought, currently there is no way to see which mouse phenotype matched the human one. And also, I think the hover over would make more sense (or the hover over could be the subusuming phenotype instead, and the matched one on the right panel.)

**Comment by nlwashington** [comment]
okay, there seems to be much confusion here.  the data is there, but perhaps needs some cleanup or things need to be explained.
1. the phenogrid widget calls owlsim, which accesses comparisons for genes and diseases (not genotypes).  genotypes are not loaded into the owlsim server at the moment.  this is why genes are the columns for mouse, and not genotypes.  all phenotypes that are originally annotated to the genotype are propagated to the gene before loading into owlsim (and currently for owlsim, only single-gene genotypes are loaded).
2.  there are two problems that underlie @mellybelly bug.  first, what appears to be happening is what is displayed for the hover is exactly what is rendered in the right-hand column, but this behavior is not what is desired.  let's take for example, OMIM:600634, which has a single phenotype, "Pituitary prolactin cell adenoma". the underlying call to the server is

http://localhost:8080/simsearch/phenotype/?input_items=OMIM_600634&target_species=10090

the top hit for mouse is to Rgsc1328:  the object has the following structure:
        "b": {
            "id": "HP:0002666",
            "IC": 10.170783876380423,
            "label": "Pheochromocytoma"
        },
        "a": {
            "id": "HP:0006767",
            "IC": 13.064252994296565,
            "label": "Pituitary prolactin cell adenoma"
        },
        "lcs": {
            "id": "HP:0100568",
            "IC": 8.465468375513037,
            "label": "Neoplasm of the endocrine system"
        }

where "a" is the query/human term, "b" is the target/mouse term, and "lcs" is their common subsumer.  what is currently rendered in the matrix is "neoplasm of the endocrine system" for BOTH the right-hand column AND for the hover behavior.  but what should be rendered for the hover text behavior is the label for "b", which is "Pheochromocytoma".  

the other issue is that the original "MP" annotation is not displayed for the target/mice.  this is because of the way owlsim works; the original MP class, MP:0002050, is equivalent to the class HP:0002666, and when the ontology is built one of these classes is chosen as the representative element (in this case, HP).  i don't believe that owlsim keeps track of the original annotation (does it, @cmungall).  since the two classes are equivalent, it "logically" doesn't matter which one is chosen.  

that said, i understand the desire for the MP term to be displayed.  that will take some more time to figure out to refactor some code.

**Comment by frdougal** [comment]
Thanks for the information .  Can we discuss this during a call?  I want to make sure I am displaying everything correctly.  I just pushed some changes to tartini.  I added a "no data found" version of the model viewer if you select something with no data (ex: choose zebrafish in the model viewer for http://tartini.crbs.ucsd.edu/disease/OMIM_127750).  This fixes bug #310

Chuck
