### ISSUE TITLE
Gene link in model viewer throws error

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#318]
See for example:
http://monarchinitiative.org/disease/OMIM_259775
http://monarchinitiative.org/gene/MGI_5491171

TypeError: Cannot call method "match" of undefined
lib/monarch/api.js, line 4699

Script Stack

```
at lib/monarch/api.js:4699 (anonymous)
at lib/monarch/api.js:3828 (anonymous)
at lib/monarch/api.js:3880 (anonymous)
at lib/monarch/api.js:712 (anonymous)
at lib/monarch/web/webapp.js:902 (anonymous)
at stick/lib/middleware/route.js:215 (route)
at stick/lib/middleware/params.js:102 (anonymous)
at stick/lib/middleware/static.js:62 (static)
at /var/home/bamboo/start-monarch-server/lib/monarch/web/sanitize.js:7 (anonymous)
at stick/lib/stick.js:37 (app)
at ringo/jsgi/connector.js:42 (handleRequest)
```

**Comment by harryhoch** [comment]
Poked around this a bit - it looks like it's a problem with the /gene/MGI_5491171 call, independent of the model viewer.

As far as I can tell, it looks like the problem is in fetchGeneInfo(). This call fails on fetchGeneInfoFromMyGene(), which leads to  call to mapGeneToNCBIGene(). The resulting call to 

http://neuinfo.org/servicesv1/v1/federation/data/nlx_152525-4.json data={"exportType":"data","count":1000,"q":"*","filter":["source:NCBIGene","mapped_id:\"MGI:5491171\""]}

returns zero records:
{"result":{"resultCount":0,"nifId":"nlx_152525-4","result":[],"debugInfo":"_:_","results":{"row":[]}},"query":{"clauses":[{"category":null,"property":null,"query":"*","expansion":[],"id":null,"quoted":false,"require":false,"forbid":false}],"operator":"AND"}}, 

which can't be parsed out. 

@kshefchek, Is this might be a of gracefully failing when no data is available, or do we need to check yet another resource?

**Comment by kshefchek** [comment]
I ran into a similar issue last week (see #307 and #308), whats happening is that we're sending a null value to the quote() function, in that function we call match on the null parameter that returns this error.

Right now fetchGeneInfo doesn't populate the gene.id value until we find the mapped NCBI gene ID.  I think the best thing to do is set the gene.id value as a default to equal the ID in the URI, and then update this if an NCBI gene ID is found. This should get rid of any issues with null values associated with the gene.id value.
