### ISSUE TITLE
can't reach digeorge syndrome from search - bad escaping

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#319]
i tried to get to DiGeorge Syndrome by entering this phrase in the search box.

it matches the term "Digeorge Syndrome/velocardiofacial Syndrome Complex 2"

however, when it escapes it and tries to get there, i get a 404:
http://monarchinitiative.org/search/Digeorge%20Syndrome%2Fvelocardiofacial%20Syndrome%20Complex%202

**Comment by cmungall** [comment]
Encoding issue. The quick fix is for the autocomplete to construct the /search/ URL is such a way that non alphanumeric characters are avoided. This is related to the other issue on apostrophes (Parkinson's disease). We need to make sure that the same results are given in the search as in autocomplete.

Of course, if you autocomplete on a term then it should take you directly to that page rather than an intermediate search page with 1 result

**Comment by debanks** [comment]
I will recommend giving this a look: http://www.leakon.com/archives/865

Typically in NIF we have taken the %25 (% encoding) approach, but it has it's own issues with trying to be consistent since you'll be expected a double encoded string now.

**Comment by kshefchek** [comment]
See duplicate #288

@nlwashington is the current fix sufficient to close

[http://beta.monarchinitiative.org/search/Digeorge Syndrome%2Fvelocardiofacial Syndrome Complex 2](http://beta.monarchinitiative.org/search/Digeorge Syndrome%2Fvelocardiofacial Syndrome Complex 2)
Does not work, but this does:

[http://beta.monarchinitiative.org/search/Digeorge Syndrome/velocardiofacial Syndrome Complex 2](http://beta.monarchinitiative.org/search/Digeorge Syndrome/velocardiofacial Syndrome Complex 2)

**Comment by nlwashington** [comment]
yes, i believe this is fine.
