### ISSUE TITLE
model viewer not showing on prod

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#335]
Not sure what happened, but it seems to be hidden? see screen shot.
@cmungall @cborromeo @BeckyBoes 

![missingmodel](https://cloud.githubusercontent.com/assets/796636/2931239/faa8bf4e-d7a0-11e3-9caa-cbbd923ffbfd.png)

**Comment by frdougal** [comment]
This happens when zero phenotypes or models are returned for a disease.  Looking at the screenshot, this text indicates there are zero models returned: "Matches [1-0] out of 0".  There is a problem with the data being returned by OWLSim for this disease.  This URL returns a 500 error:

http://monarch.monarchinitiative.org/simsearch/phenotype/?input_items=HP:0000006,HP:0000248,HP:0000545,HP:0000577,HP:0000749,HP:0000752,HP:0001513,HP:0002019,HP:0002307,HP:0005469,HP:0005484,HP:0005484,HP:0006979,HP:0008872,HP:0010808,HP:0010864,HP:0200085,HP:0000154,HP:0000154,HP:0000157,HP:0000158,HP:0000164,HP:0000272,HP:0000303,HP:0000303,HP:0000327,HP:0000486,HP:0000486,HP:0000490,HP:0000635,HP:0000639,HP:0000687,HP:0000708,HP:0001010,HP:0001250,HP:0001250,HP:0001252,HP:0001252,HP:0001270,HP:0001344,HP:0001347,HP:0001347,HP:0002120,HP:0002120,HP:0002136,HP:0002167,HP:0002286,HP:0002311,HP:0002312,HP:0002353,HP:0002353,HP:0002650,HP:0003745,HP:0004299,HP:0006887,HP:0007240,HP:0100543&target_species=10090

**Comment by frdougal** [comment]
On a related note, I think I addressed this issue on a recent update to git.  The change is now checked into github.  If the viewer returns zero phenotypes or models, the view returns an "empty" view of the data (see attached)
![screen shot 2014-05-09 at 2 00 40 pm](https://cloud.githubusercontent.com/assets/5503816/2931443/e9b279a2-d7a3-11e3-9ad5-7675ab4f4f4c.png)

You can see this on tartini if you select zebrafish for this disease:

http://tartini.crbs.ucsd.edu/disease/OMIM_127750

**Comment by mellybelly** [comment]
hmm- this is Angelman's syndrome, so we know its not zero results. 
I like the new display

**Comment by frdougal** [comment]
I used a partial list of Angelman syndrome phenotypes to open the simsearch URL in my browser.  The list returns some data when I run it on tartini.  I think Chris or Nicole needs to look into this.

Attached is a screenshot if I try to open the same URL on monarch initiative (http://monarch.monarchinitiative.org/simsearch/phenotype/?input_items=HP:0000303,HP:0000327,HP:0000486,HP:0000486,HP:0000490,HP:0000635,HP:0000639,HP:0000687,HP:0000708,HP:0001010,HP:0001250,HP:0001250,HP:0001252,HP:0001252,HP:0001270,HP:0001344,HP:0001347,HP:0001347,HP:0002120,HP:0002120,HP:0002136,HP:0002167,HP:0002286,HP:0002311,HP:0002312,HP:0002353,HP:0002353,HP:0002650,HP:0003745,HP:0004299,HP:0006887,HP:0007240,HP:0100543&target_species=10090)

![screen shot 2014-05-09 at 2 10 16 pm](https://cloud.githubusercontent.com/assets/5503816/2931618/b0c2b376-d7a5-11e3-9c51-dd38f563569d.png)

**Comment by cmungall** [comment]
Fixed with owlsim server restart
