### ISSUE TITLE
no suff score showing for NCBIGene:20423

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#339]
i checked here:

http://localhost:8080/gene/NCBIGene:20423

but no sufficiency score is showing up.

**Comment by kshefchek** [comment]
The issue here was that getAnnotationSufficiencyScoreFromAssociations(phenotype_associations) was being called after generating gene-phenotype relationships for human data.  I moved this to the end of fetchGeneInfo() and this should work now for model organisms.  
See: http://tartini.crbs.ucsd.edu/gene/NCBIGene:20423

**Comment by nlwashington** [comment]
the tartini link is broken, and it doesn't seem to work on stage:
http://stage-monarch.monarchinitiative.org/gene/NCBIGene:20423

**Comment by kshefchek** [comment]
I think the tartini issues were related to owlsim being down this afternoon, the link should be working now.  This probably hasn't been pushed to stage-monarch yet.

http://tartini.crbs.ucsd.edu/gene/NCBIGene:20423

**Comment by cmungall** [comment]
I pushed a fix to owlsim, should be working on tartini now
