### ISSUE TITLE
add scrollbars to phenogrid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#416]
we need the scrollbars back in the phenogrid.  (although, better ones than we had before.)

the minimap is very awesome to get an overall view of the data, particularly over the "population" of results.  but as a means to navigate, i think it lacks something familiar.

things i can't do now, that i would if i had a scrollbar:
- increment the viewable window by one  (for both cols or rows)
- quickly get to a specific portion of the window by tapping once.  (the map only allows dragging).

**Comment by harryhoch** [comment]
We should think about requests like these in terms of functionality, not implementation. Incrementing the viewable area by one and quickly going to a specific portion of the window are good goals that might be achieved multiple ways. We can easily change the overview window to be click-based instead of drag, and arrow icons might help with scrolling (as the overview window already provides the location awareness that is a key component of scrollbars)...

**Comment by nlwashington** [comment]
also see https://github.com/monarch-initiative/phenogrid/issues/22

**Comment by harryhoch** [comment]
moved discussion to https://github.com/monarch-initiative/phenogrid/issues/139
