### ISSUE TITLE
configuration for phenogrid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#464]
In order to make the phenogrid a bit more general to allow EITHER comparison to a selected set of targets (such as orthologs) OR to show the results of a search, i think it needs a configuration panel.

Here's a mockup of a configuration panel. (I have the Basalmiq file if you want to modify.)
![config_mockup](https://cloud.githubusercontent.com/assets/5124411/3591873/8e95b94e-0c69-11e4-8a29-c2bfe98ec82e.png)

The idea here is that the user can select the kind of data they want to see in the grid display (either the result of a search as we have now, or a comparison to a user-selected set of targets), with a few configurable options. Then, upon clicking a button it executes the data fetch and display. 

Each of the configuration options on the left corresponds to a parameter to be submitted to the API call, and can be accommodated now.  The compare call on the right will require a bit of wrapping, but the idea would be that the results of the search and compare calls would be identical, and all you'd have to do would be to execute a different call.  The "shortcut" buttons would provide a way for the user to easily select a common set of targets (actions that are probably done often).  For example, after searching for a gene "shh", the user could click the "homologs" button, and all the homologous genes of shh would be added to the gene list box below it.  That way, in one click, the user fetches that bunch of gene ids (we could also think about showing the list in a better way).  And they could do this with one or more of the shortcut buttons.  Alternatively, the user could just paste a set of ids into the box with which to compare their query to.

The advanced section is maybe a bit premature, but good to think about.  The mockup shows some inferencing rules that the user might want to regulate.  For example, they would select genotype-->gene if they want to allow all phenotypes that are directly annotated to a genotype to be applied to a gene.

Of course, this is just a mockup of some ideas.  @harryhoch @mellybelly and @cmungall should comment on design.

**Comment by harryhoch** [comment]
Nicole

Nice. This would take a bit of doing, but I think we can come up with something. I will give it some thought.

One quick response to think about is the notion of “overview first”.  Generally, it’s good to give people something to start with, without requiring that they make several selections before seeing data. I think we can probably work something out that will combine overview with configurability, but we’ll have to give it a bit of thought.

harry
On Jul 15, 2014, at 4:44 PM, Nicole Washington <notifications@github.com<mailto:notifications@github.com>> wrote:

In order to make the phenogrid a bit more general to allow EITHER comparison to a selected set of targets (such as orthologs) OR to show the results of a search, i think it needs a configuration panel.

Here's a mockup of a configuration panel. (I have the Basalmiq file if you want to modify.)
[https://cloud.githubusercontent.com/assets/5124411/3591054/ee011a18-0c5f-11e4-8e09-912b197abefe.png]https://cloud.githubusercontent.com/assets/5124411/3591054/ee011a18-0c5f-11e4-8e09-912b197abefe.png

The idea here is that the user can select the kind of data they want to see in the grid display (either the result of a search as we have now, or a comparison to a user-selected set of targets), with a few configurable options. Then, upon clicking a button it executes the data fetch and display.

Each of the configuration options on the left corresponds to a parameter to be submitted to the API call, and can be accommodated now. The compare call on the right will require a bit of wrapping, but the idea would be that the results of the search and compare calls would be identical, and all you'd have to do would be to execute a different call. The "shortcut" buttons would provide a way for the user to easily select a common set of targets (actions that are probably done often). For example, after searching for a gene "shh", the user could click the "homologs" button, and all the homologous genes of shh would be added to the gene list box below it. That way, in one click, the user fetches that bunch of gene ids (we could also think about showing the list in a better way). And they could do this with one or more of the shortcut buttons. Alternatively, the user could just paste a set of ids into the box with which to compare their query to.

The advanced section is maybe a bit premature, but good to think about. The mockup shows some inferencing rules that the user might want to regulate. For example, they would select genotype-->gene if they want to allow all phenotypes that are directly annotated to a genotype to be applied to a gene.

Of course, this is just a mockup of some ideas. @harryhochhttps://github.com/harryhoch @mellybellyhttps://github.com/mellybelly and @cmungallhttps://github.com/cmungall should comment on design.

—
Reply to this email directly or view it on GitHubhttps://github.com/monarch-initiative/monarch-app/issues/464.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics
harryh@pitt.edumailto:harryh@pitt.edu  412 648 9300

**Comment by mellybelly** [comment]
@harryhoch I know progress on config has been made, but no UI for this yet. So I will push this off to November?

**Comment by harryhoch** [comment]
yes, please

**Comment by kshefchek** [comment]
We will need an explanation of what the search and compare functions do.  I can add a sentence under each radio button or add an icon that is either clickable or shows some information when hovering (similar to the information icon on the phenogrid).

**Comment by kshefchek** [comment]
This is what I have as a placeholder:
Search: Search for model genes, genotypes, and semantically similar diseases 
Compare: Compare phenotypes agaisnt a set of genes

**Comment by kshefchek** [comment]
@nlwashington is what has been done on the new analyze page sufficient to close this in favor of more specific tasks?

**Comment by harryhoch** [comment]
@nlwashington, we should have a general discussion of configuration needs in phenogrid...

**Comment by harryhoch** [comment]
still to be done - https://github.com/monarch-initiative/phenogrid/issues/141
