### ISSUE TITLE
Use pup_tent framework for rendering pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#482]
See @kltm/pup_tent & https://github.com/kltm/go-mme/issues/73

Best done on a branch when we have a suitable hiatus

**Comment by nlwashington** [comment]
@kshefchek  - @kltm added an initial pass with puptent by refactoring our main page.  see http://monarchinitiative.org/labs/blog-scratch.

we'd like all webpages to be refactored cleanly here.  there are some issues with the way bootstrap has been used in the current web implementation, and it needs to be cleaned up.  can you work on this on a branch?

**Comment by kshefchek** [comment]
Sure, I'll create a puptent branch and test there.

**Comment by kltm** [comment]
https://github.com/kltm/pup-tent

which has underscore.js as a dependency.

The version of pup tent in blog-scratch is an earlier version. The API has changed a little, but works mostly the same. If you have any questions, I can point to how it is used other places.

I'm guessing that the refactoring in the core bits will cause quite a lot of churn, making merges harder. You might want to consider freezing those parts or getting other people working on those parts to use your branch during the transition.

**Comment by kltm** [comment]
@cmungall Wait, sorry, brain is fully engaged now.

Pup Tent was written for Node.js. While there are no deep dependencies, the files access stuff would have to be abstracted to use in Rhino. I'm guessing an hour or so (file handling initializer that probes the environment and connects the abstract function to the real one).

**Comment by kltm** [comment]
Underscore and mustache already run everywhere, so Pup Tent file access is the only issue.

**Comment by kltm** [comment]
Works for RingoJS now as well.

**Comment by kshefchek** [comment]
@kltm, I'm getting an error when testing pup-tent:

TypeError: Cannot find function render in object [object Object].
    at pup-tent.js:318 (_apply)
    at pup-tent.js:374 (anonymous)
    at /home/kshefchek/git/monarch-app/tests/full-tmpl.js.tests:13 (anonymous)
    at /home/kshefchek/git/monarch-app/tests/full-tmpl.js.tests:8

Have you seen this error or have an idea where I'm going wrong?

Branch is here:
https://github.com/monarch-initiative/monarch-app/tree/puptent

Command:
./ringojs/bin/ringo -m ./modules/pup-tent/ -m ./modules/underscore/ -m ./ringojs/modules/ringo/ tests/full-tmpl.js.tests

**Comment by kltm** [comment]
@kshefchek My first guess would be that you have not met the dependencies of the module:

 https://www.npmjs.org/package/pup-tent

In particular, after checking out your branch, I think that you might need mustache more handy.

Unfortunately, IIRC, npm is Node.js oriented, so you'll have to get the dependencies yourself.

**Comment by kshefchek** [comment]
So adding mustache to the modules directory solved this (if no output means the test passed).  But now we have mustache duplicated in both the ringo directory in our modules directory.  I assume moving forward we will have to redirect any require mustache calls to the modules directory.

**Comment by kltm** [comment]
@kshefchek No output in this case does indeed mean that they passed (you can see this by breaking a test), returning a good code.

**Comment by kshefchek** [comment]
I've updated webapp.js and our mustache templates (using a common base template when possible) to use pup_tent.  In testing everything is working with the exception of the phenogrid where I'm seeing some noticeable differences that need to be investigated.  I'll be taking a look at this over the next few days.

Also, I've copied the design from the go-mme project in which all static js and css files are routed to the top level directory.  This caused one naming conflict (search.js and our search page) which I resolved by renaming search.js to search_form.js.  There could also be an issue with routing javascript files from the widgets directory if say we use a different version of D3 in one of our widgets but not in our main app (since version number is not included in the file name).  For now this should be fine since we're using the same version of d3 in both places, but perhaps we should come up with more intelligent routing, @kltm thoughts on this?

All devs please pull/push to the puptent branch if editing webapp.js or any mustache templates to avoid merging conflicts.

**Comment by kshefchek** [comment]
After investigating, the issue with the phenogrid was caused by having two different copies of modelviewer.css in the /css/ directory and the widgets directory.  Pup-tent was using the widgets version while the /css/ version is what we need.  I've renamed the css file to avoid this, although we should probably copy the correct file into the widgets directory.

@kltm, is there a way to turn off caching temporarily, for example when working on a non-production branch.  While debugging I realized I could no longer update static files and see changes immediately without restarting the server.  This could be a bit of pain when editing our static scripts.

So this is ready to go whenever we want to make the switch.  I'm able to merge the master branch into puptent without conflicts.

**Comment by kltm** [comment]
If I'm following, the caching is a separate area from templating and they can be used independently (or not at all). It would all depend on how the caching has been woven into your dispatch code.

It would probably be pretty easy to add a patch to be able to toggle back and forth between the two however.

**Comment by kshefchek** [comment]
That's correct, I'm thinking more development of static javascript and css files, for example when developing our front end widgets (phenogrid, keggerator, etc.).

**Comment by kltm** [comment]
There should be API docs for this now as well:

 https://kltm.github.io/pup-tent/
 https://kltm.github.io/pup-tent/docs/files/pup-tent-js.html#use_cache_p

I think it should work, but not technically tested on ringo yet.

**Comment by kshefchek** [comment]
Updated to include @kltm 's new function for our dev environment, see https://github.com/kltm/pup-tent/issues/2

**Comment by kshefchek** [comment]
Merged into master, closing.
