### ISSUE TITLE
Analyze Phenotypes doesn't show query

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#484]
From @drseb. See related tickets on #243 

my startpoint was: http://monarchinitiative.org/phenotype/ .

I then clicked on "Sample patient phenotype profile”. The following page shows a list of results. For me as a user I miss, what I have actually been using as a query. I see some query Term-IDs in the URL, but I think this should be shown somewhere. Also under the tab “Query” I can’t find my query. 
According to the URL there are several MP-terms used for this example, but when I click on "Sample patient phenotype profile” I would expect HP-terms, since ‘patients’ are normally not annotated by MP.
Finally when I click on “Grid View”, it shows a blank tab.

I used Firefox 30.0 on MacOS 10.9.4

**Comment by boesb** [comment]
The blank grid issue is fixed and checked into the master branch but not yet on production.

**Comment by iamkoehler** [comment]
Melissa replied (via email) "The MP ids show because the primary ID is chosen randomly from Uberpheno randomly where there are equivalencies."

For vertebrate-merged.owl, Chris actually has a weighting, such that HP-ids are preferred among HP and ZP. Also this would mean that for each query-term in this example there exists an equivalent MP-id and additionally that this MP-id is randomly chosen. In the URL I don't see any HP at all.

The link URL is : http://monarchinitiative.org/analyze/phenotypes/?target=ZFIN&input_items=MP%3A0000788%0D%0AMP%3A0000822%0D%0AMP%3A0000914%0D%0AMP%3A0000929%0D%0AMP%3A0000930%0D%0AMP%3A0001286%0D%0AMP%3A0001393%0D%0AMP%3A0001688%0D%0AMP%3A0001698%0D%0AMP%3A0001732%0D%0AMP%3A0001787%0D%0AMP%3A0002064%0D%0AMP%3A0002083%0D%0AMP%3A0002151%0D%0AMP%3A0002950%0D%0AMP%3A0003012%0D%0AMP%3A0003424%0D%0AMP%3A0003651%0D%0AMP%3A0004948%0D%0AMP%3A0005657&limit=100
