### ISSUE TITLE
Compare not working for 2 genes that share a phenotype

### ISSUE THREAD

**Issue by gnewton** [monarch-initiative/monarch-legacy#504]
I tried to compare 2 genes using /compare/:x/:y.json :
1 - Went to this phenotype: http://monarchinitiative.org/phenotype/MP_0000849
2 - Chose first and third on list: TINF2, RBM8A
  http://monarchinitiative.org/gene/NCBIGene:26277
  http://monarchinitiative.org/gene/NCBIGene:9939
3 - Compare:
http://monarchinitiative.org/compare/NCBIGene:26277/NCBIGene:9939.json
http://monarchinitiative.org/compare/26277/9939.json

Zero results for both, despite both genes having phenotypes and sharing (at least) one, MP_0000849

My understanding from http://monarchinitiative.org/page/services is that this should be valid: "Currently services are only supported for a subset of entities in the system - those with phenotypes. "

**Comment by nlwashington** [comment]
@gnewton you are correct, this does not work.  i believe this isn't working at the moment because those two genes are Homo sapiens, and the phenotypes related to all homo sapiens genes are inferred.  at the moment, our owlsim server is configured to run the "compare" on those entity IDs who's phenotypes are directly associated (rather than inferred).  of course, since we didn't provide a report on exactly what is available for owlsim entity comparison, you wouldn't know that...it just so happens we only have loaded direct assertions for mouse, fish, and fly genes.  

@cmungall we could immediately fix this by wrapping the compare function with a lookup to fetch the inferred phenotypes, and send those into the compare function.  longer-term, we should probably do the inferrencing in owlsim itself and include the gene-disease relationships.  should i go ahead and write the wrapping function (then assign to me)?

**Comment by gnewton** [comment]
Any ETA on this?  :-)

**Comment by nlwashington** [comment]
@gnewton i have fixed up the function in 9bbcd5c.  this fxn had underspecified functionality, and i don't believe it is actually used by any of our current widgets.  it currently returns the scored pairwise comparisons of phenotypes from each (x,y) in the comparison.  is there anything else you'd like to get back?  you can test it out on our beta, http://tartini.crbs.ucsd.edu/compare/NCBIGene:26277/NCBIGene:9939.json.

**Comment by nlwashington** [comment]
also, comparisons are currently limited to individual phenotype ids, disease ids, and NCBIGene identifiers.  we are working on an identifier resolver for other types.

**Comment by gnewton** [comment]
That is great! U guys rock! I owe u beers!  :-)
Do you know when this will be moved to production? Or are you OK with me querying beta?

**Comment by nlwashington** [comment]
so long as you don't build our beta services into any downstream production system, i'm ok with you querying beta.  caveats:  it gets the latest software updates (restarted upon code commit), but along with that it is more fragile, subject to downtime, and new services are subject to change;  it is slower (as it doesn't run on prod hardware).  i expect it will move to prod in a month or so.

**Comment by nlwashington** [comment]
fyi, i had been meaning to refactor the compare function to deliver results in the same format as the simsearch function.  i will work on that refactor now.  see #352.

**Comment by nlwashington** [comment]
note that i have done a bit of refactoring in commit 968d396, and now the output of this function will be identically formatted to the search output, and you can do a set of comparisons (one query multiple targets), like:  http://tartini.crbs.ucsd.edu/compare/OMIM:270400/NCBIGene:18595+OMIM:249000+OMIM:194050.
so, you will also get an overall comparison score for each target, which is based on a maximal score of the query to itself.
