### ISSUE TITLE
revise home page 

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#518]
suggested layout https://docs.google.com/drawings/d/1sqBm8j-MjN-cqv-rvN2Lbse3kZy2FUFKGPsjWtAyj5o/edit

**Comment by kltm** [comment]
@harryhoch the linked document seems to require permissions; could you make it more openly viewable?

**Comment by kltm** [comment]
New subtasks now: https://github.com/monarch-initiative/monarch-app/issues/518#issuecomment-55322513

<strike>_This_ _item_ _will_ _be_ _updated_ _as_ _this_ _issue_ _progresses_.
The current subtasks are:</strike>
- <strike>revisit labs template and integrate any details from other parts of the site</strike>
- <strike>create some kind of caching for the news feed (so we don't always have a synchronous block)</strike>
- <strike>create a new labs page for the front page that incorporates @harryhoch's layout plan</strike>
- <strike>maybe toy with the main graphic to get it more compact</strike>

**Comment by harryhoch** [comment]
@kltm, oops -sorry. here it is. 
![home page mockup20140724](https://cloud.githubusercontent.com/assets/174707/4156335/5035531c-3473-11e4-831f-af7b8afe56a6.png)

**Comment by kltm** [comment]
Whoops--I guess "puptent" is my working branch for this--makes sense I guess; and it was defunct anyways.

One point finished from above: caching done.

**Comment by kltm** [comment]
It looks like the house style has drifted a bit since the earlier mock-up, will take a little work to get things back up to speed.

**Comment by kltm** [comment]
All of the subtasks originally listed above are completed. The labs prototype page is now far enough along that needs/wants/time need balanced. The page is _not_ meant to be the prototype, but is designed to highlight issues that need to be decided on the way there.

The (puptent) branch is it more BS3-style than previously, with a two row layout and steps at small (cell), medium (tablet), and large (desktop). The rows more-or-less follow @harryhoch's layout, except for the fact that vertical spacing is hard when dealing with a reactive layout (an issue further highlighted below).

General changes are the removal of the jumbotron (which had some problems and didn't really fit anymore) and making the footer a real element (preference, didn't like the disappearing one, especially since whole pages are now being created).

Issues to discuss are:
- Main graphic compaction (not a mockup)
- Main graphic size and behavior at scale levels
  - moving away from graphic? does the replacement scale?
- D3 vs static img: size guarantee vs dynamic scaling/rewrite code
  - example shows what can happen to D3 without extra scaling support code
- Blog now runs every half our on refresh
- "Naked" framing of entry points: real estate valuable?
- Resource ticker...not much to say there I guess; a different kind of panel-less framing
- Social: ticker vs static links out (suggestion: static, let blog drive)

Again, all currently on puptent, but may be easier on master for demo (nothing relevant likely changed except switching to versioned version of puptent, instead of the dev repo download).

**Comment by harryhoch** [comment]
Seth: I assume I should be looking at the labs/blog-scratch page to see this? It looks very nice. 
One thing that we might want to add would be the as-of-yet unwritten one-sentence tag line describing what Monarch is about... 

Regarding those outstanding issues, the D3 scaling seems to be a potentially big one. Some of the others are probably secondary issues..

**Comment by kshefchek** [comment]
The graph widget allows for resizing of the graph area on the client side, so we could check the user's screen resolution and adjust accordingly if needed.

**Comment by kltm** [comment]
_New_ _marching_ _orders_ _from_ _today's_ _meeting_; _this_ _item_ _will_ _be_ _updated_ _as_ _things_ _progress_.
- <strike>Main image should now be carousel; use current four as mockup base</strike>
  - <strike>find better carousel lib than the nastiness that GO uses</strike>
- <strike>Current "Data Overview" should be exp text and links to graphs, etc.</strike>
- <strike>"News and Events" needs to be tightened</strike>
- <strike>Add "Models"(?) to entry points</strike>
- See what can be done about tweets (would need access to account)
- <strike>Data ticker needs to be a little more compact; have real data</strike>
- <strike>merge puptent back into master for easier demos</strike>
  - get somebody to check/rollout new base
- <strike>figure logo and related reflow</strike>
- <strike>add carousel glyphs</strike> (good enough for now)
- <strike>add "more" to bottom of blog</strike>

Another major thematic takeaway was: definitely "yes" on full Bootstrap/reactive working for smaller formats, even at the cost of some interactivity (re: @kshefchek's graphs).

**Comment by kltm** [comment]
Hating git right now, but cleanly merged.

**Comment by kltm** [comment]
New version up, covering most of what was discussed this morning to:

 http://tartini.crbs.ucsd.edu/labs/blog-scratch

Somebody will need to create the widget in the twitter account to get that properly working (instead of using GO's). Also, people will probably need to start adding meat to the bones to get an idea of what this needs to be.

**Comment by kltm** [comment]
@mellybelly to spec out phenotype of the month (if separate from the blog feed--keep in mind that the blog could be tweaked to do some of this stuff, but too much and we'll need to switch to a better hammer).

**Comment by nlwashington** [comment]
i have added a bit of content to the page: http://tartini.crbs.ucsd.edu/labs/blog-scratch .  i have not yet made the images perfectly sized.
@kltm there's a bunch of little items that would be good to fix:  >length of time between slide transitions, css for how the text looks on the slides themselves (maybe it would be better below?, non-white).  

i think there's too many slides, so suggest ones to cut.  i'm thinking we might consider re-combining the different "things" into a single slide again, but i'll await feedback.

in doing this, i think we should remove the middle panel from the bottom row and expand the left panel to fill the space.  i've put a simple sources slide into the carousel as a substitute.

**Comment by nlwashington** [comment]
i have now added our first real blog post, and it looks terrible on the home page... it's attempting to render the full post, complete with html markup.  perhaps this should be limited to the blog title, and/or a fraction of the text?

**Comment by cmungall** [comment]
Now just passing the html through directly. I'm _pretty sure_ this is safe...?

**Comment by nlwashington** [comment]
know why the date of the blog post in the news ticker doesn't match that on the blog post?  it shows up in the ticker as 2014-08-19, but the date of the post should be 2014-09-14 (it shows it as September).

**Comment by nlwashington** [comment]
so after spending a fun friday evening browsing the web to determine what it is i like (or don't) about websites and templates, i am not in love with this template (though it's better than our current one!)

i found this, which is kinda neat .  http://wrapbootstrap.com/preview/WB0C06H5D. (although make sure you mute because there is an annoying autoplay video in the demo).
i don't know anything about templating, and i'm not suggesting that we have to use these ones for purchase (although there is a license we can purchase for redistribution purposes), more that i was just looking at general layouts.  i have no idea how modifiable/extendable the code is.

**Comment by kltm** [comment]
We currently use no additional styles in addition to the vanilla bootstrap. We can move on to theming once we've cleaned the rest of the monarch code and understand how to get all of the widgets and bootstrap working together. For now, I think we should mostly be worrying about content and figuring out what needs to be on the front page.

**Comment by kltm** [comment]
For blog, publish date replaced with modification date in feed.

**Comment by nlwashington** [comment]
ok, i really like this site's homepage:  http://nectar.org.au/
it's clean.  it's simple.  it's modern.  we need to convey modern.  
*we can fill in the "what is" with links to the new about page that i'm writing, and a few more pages that i'm dreaming up.  i think introductory material to our site is going to be enormously important.
*the four big block buttons would have the four categories that were recently converted to tabs on our current redo...browse,discover,learn,contribute.  (this will require that each of those have it's own page for jumping off too, which is fine.)  unfortunately these somewhat map to the top-level menu items.  i don't necessarily want that either, but maybe it's fine for now.  (we should just make sure that they are somewhat in synch language-wise)
*i can strip our current carousel down to just a couple of items (probably 4 max).
instead of "researchers", maybe put in there "collaborators" or "partners" that could be a slowly rotating list where we describe them.  
*then we'd have our blog-based news feed (not scrolling) and our twitter feed.

**Comment by nicolevasilevsky** [comment]
I like it too! I made a mockup based on that page.
![frontpage_nv](https://cloud.githubusercontent.com/assets/6722114/4378909/39519064-435c-11e4-9608-8e998f3ae981.jpg)

**Comment by nlwashington** [comment]
@kltm i'm liking the way /labs/blog-scratch is coming along.  i've added a few items in the "about" and updated the links for the Explore panel.

Why are there two searches?

**Comment by kltm** [comment]
I was stopping before going on to fiddly (large time investment, low rate of return) items to make sure there was broad consensus on where this was going. Unfortunately, I probably won't be able to get back to this until after the GO meeting.

**Comment by kltm** [comment]
Two takes on the home page from last round of feedback:
http://tartini.crbs.ucsd.edu/labs/blog-scratch
http://tartini.crbs.ucsd.edu/labs/blog-scratch-exp

**Comment by cmungall** [comment]
I like exp

I assume we'd need to find/make our own background

**Comment by kltm** [comment]
Yes, naturally--I threw that together to give an idea of what a dark background splash might look like. If If people like "-exp", somebody would have to get images.

**Comment by harryhoch** [comment]
agree - +1 on exp.  Nice work, @kltm. I love the idea of overlaying the phenogrid and datagraph on the images. Can we get some good danio or mice images?

One nitpick - can we get the bottom of the twitter widget to align with the bottom of the news widget?

**Comment by kltm** [comment]
If people can supply images with black backgrounds, or ones that can be moved to black backgrounds, we can rotate those in. The current images should be removed due to the fact I scraped random "biology" pictures off of wikipedia. Preferably public domain, but we can add them to maybe the about page and/or at the bottom if it is some kind of cc-by.

As for the nitpick, I think that would actually be rather hard given the reflow (responsive layout) and the fact that the widget is not really under our control. The best we could easily do would be to get the shape of the news feed to mostly match.

**Comment by harryhoch** [comment]
Seth,  adjusting the height of the news widget would be fine. Is it hard to trim a few pixels off the height to match the twitter widget?

There's a similar problem across the two columns that I didn't catch earlier.  Ideally, the bottom of the about box would align with the bottom of the search box, and the top of the explore would align with the tops of tweets and news events. How hard is that to fix?

**Comment by kltm** [comment]
@harryhoch I'm not sure I'd think of it as a problem as much as an artifact of how we decided to do things (BS3/responsive). While one could trim here and there, it doesn't really matter since there is no actual set sizes in this type of responsive layout. As an example, set your browser to a quarter of your screen size and then manually change the window's dimensions vertically, horizontally, diagonally--you'll see that besides the gross two-column layout (which collapses into a single column after a certain point), every panel leads its own sizing life, only caring about the larger row structure; this is part of what makes the responsive layout work in this case. (You'll also notice that the twitter widget will get smaller than its original render size, but not larger, which is a bit irritating, but outside our direct control.) Essentially, we get something reasonable at every possible size and dimension set (in fact, take a look on cell phones and small tablets), at the cost of being too worried about lining things up.

Now take a look at http://ericclapton.com/ , which is essentially the opposite in every sense. Besides any other issues, it is designed to be viewed a single way, with no leeway for variable window sizes.

There are some small things we can do later on, like trying to set minimum sizes in certain contexts, but the process is fiddly and time consuming.

**Comment by harryhoch** [comment]
@kltm, I see your point about responsive layouts, and I am aware that nothing with ever be perfect. 
That said, it's an "artifact" from below and a  "design problem" from above - visually, it's always best to have things line up into nice grids.  Although responsive layout may make it impossible to guarantee that all panels will be well-aligned for all possible browser window sizes, i think it should be possible to get things nicely lined up for a starting point of a reasonable browser size.  I see these layout  problems at 800x800, 1024x768, 768x1024,  and 1400x900. 

That said, I am aware that this is a pain, and that nothing will ever be perfect, so I'm going to let this drop... thanks for struggling through with it...

**Comment by kshefchek** [comment]
These are both child elements of a bootstrap row class, so theoretically these should line up as you make the screen wider.  I've tried to fix it by wrapping the twitter element in a  div class="panel panel-default" so the format of the surrounding border is the exact same.  This may have fixed it but it's so close it's hard to tell.  @harryhoch @kltm does it look any better?

**Comment by kshefchek** [comment]
Nevermind, looks like this caused a double border effect with the iframe and the panel divs.  I'll see if theres any way to fix this.

**Comment by kshefchek** [comment]
I've made some updates to the News and Events section.  I added some inline styling to override the default bootstrap styling. 

Old version: http://tartini.crbs.ucsd.edu/labs/blog-test
New version: http://tartini.crbs.ucsd.edu/labs/blog-scratch-exp

**Comment by kltm** [comment]
@kshefchek I'm seeing a slight tightening and bolding of the header. If we're going to try and match the twitter widget next to it, we'll probably convert that into a proper panel anyways. Also, because of reflow, the rest of the panels to match headers, with my druthers on lighter rather than darker (and get News & Events to match the other elements in general).
Oddly, I couldn't find your css changes in the tracker...could you link to those?

@harryhoch I may honestly not be seeing the layout issues that you're seeing (except, again, for bottom row alignment). Maybe we can touch bases next Thursday.

For anybody else still following this now rather long issue, we're going to need images to replace the placeholders.

**Comment by kshefchek** [comment]
I changed the template directly, changes to blog-scratch-landing.template here:
https://github.com/monarch-initiative/monarch-app/commit/701ad5e8f14e3e57e114ba0d532488c9ed3567d2
https://github.com/monarch-initiative/monarch-app/commit/dcd7c16607c66e7b49e2e6a7937ac414bf45a81e

I changed the color and border radius of the News panel, as this seemed easier than updating the styling of the twitter timeline widget (I tried this as well)  It seems the darker color and different border radius give the illusion that the panel is sitting higher.  As you mentioned I also changed the text-weight, the padding around the header, and the position of the hr tag.

**Comment by harryhoch** [comment]
@kltm, I used the FF web developer extension to set the window size to 1024x768 and got the following. Note the lineup circled on the right.

![monarch-lab-exp](https://cloud.githubusercontent.com/assets/174707/4878179/e29a9956-6303-11e4-8846-bb4d3075cc71.png)

**Comment by nlwashington** [comment]
late to the party, but i too like -exp.  i have two issues.
first is about the order of the items when responding to a narrow 1-column layout.  i suspect a 1-column layout is what a user would observe when they are looking on a phone.  i get a little concerned that the search and explore boxes are the last two on the page...as this is major functionality and action that users would come to expect to use upon re-entry, we probably want those to be near the top, if not the first box, then the one just beneath the "welcome" box.  how hard would that be to change?

the other issue is probably unchangeable, but can the twitter box be responsive too?  for example (image below), i'm on a 1-column layout, and the twitter box is not responsive to the width, and looks funny that it's smaller than all the other 1-col things.  can that be changed?  i found this...is it helpful? http://tappetyclick.com/blog/2012/12/20/how-dynamically-resize-new-twitter-widget#.VFgRJ-fDJIU https://www.geekgoddess.com/change-twitter-widget-to-wider-than-520px/

![screen shot 2014-11-03 at 3 31 22 pm](https://cloud.githubusercontent.com/assets/5124411/4892381/8c6f0072-63b1-11e4-86f8-d6aa4a877b3d.png)

**Comment by kltm** [comment]
@harryhoch what you're seeing is due to the fact that we're not using a grid, but a two-column layout where the two columns just happen to be similarly sized at the moment. When we had the three boxes on the side (or when we will have the larger search box there), the difference is more obvious.

@nlwashington for your first issue, given the two column layout, it's pretty much all or nothing. Your change would put the search and explore boxes before the welcome on mobile, which I'm not sure would be great. I believe it could be done though, without too much problem.
For your second issue, the answer would be "we'll see"; again, that widget is not under our direct control and trying to override it too much may cause other issues. Something to play with when everything else is done.

Again, we really need to change the images. People need to get images.

**Comment by kltm** [comment]
Melissa got some more good images: #587.

**Comment by kltm** [comment]
Going to just bite the bullet and deal with non PD images.

**Comment by kltm** [comment]
Are we really keeping "See awesome stuff." as the hover text for the explore graphics?
