### ISSUE TITLE
multi-organism simsearch

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#521]
simsearch can currently only handle one organism at a time. For the phenogrid, this means that the overview must make n separate calls, one for each included organism. 

As an enhancement aimed at reducing round trips, can we support multiple organisms in a single query? This might be doable at the API layer in monarch-app, without requiring changes to owlsim services.

Bonus points if this can be done without requiring major surgery to the format of returned values...

**Comment by nlwashington** [comment]
so, the one thing about adding multiple species, is that this function currently allows the user to specify a target_species and a target_type.  should i similarly allow for >1 target_type?  and if so, should i assume that the user would desire all combinations of target_species*target_type? (even though right now it happens to map 1:1 between species and type?)

**Comment by harryhoch** [comment]
I think one target type would be sufficient, for now at least

**Comment by jmcmurry** [comment]
Could also be relevant for an uber search, so I'm tagging this accordingly.

**Comment by yuanzhou** [comment]
@harryhoch I was working on creating a nodejs server to handle REST API for another project yesterday and discovered this npm package [Async](https://github.com/caolan/async). Maybe I can use it to send parallel calls to get simsearch data back for each species. Since monarch is running on node server, those calls can be handled asynchronously. It'll be still be n separate calls but we don't have to chain those calls as we are doing now (we go through the targetGroupList recursively for each call and only fire the next call when the previous call completes).

**Comment by kshefchek** [comment]
I think this type of behavior is client driven using promises (or regular ajax calls depending on your needs), although I may be misunderstanding.

**Comment by harryhoch** [comment]
@yuanzhou, this is interesting, but I don't think it is necessary worth tackling right now. The point of a multi-organism call would be to push complexity from the client to the server. An async call might make some small improvements, but wouldn't address the main issue.

**Comment by jmcmurry** [comment]
done
