### ISSUE TITLE
The annotation sufficiency score service should accept POST parameters

### ISSUE THREAD

**Issue by sdumitriu** [monarch-initiative/monarch-legacy#533]
Sending a JSON with all the features can easily hit the maximum size allowed for GET parameters, while POST doesn't have this low limit.

Also, POST data has better privacy, since GET data is more easily snooped.

**Comment by mellybelly** [comment]
@nlwashington @cmungall can this be addressed for October release?

**Comment by kshefchek** [comment]
We can now post to this service, although sending the the post params is a little hacky since I preserved the function for both get and post on the webapp side, see https://github.com/monarch-initiative/monarch-app/blob/99536e546d17e41cba5320ba7de02f3fe1135c3a/js/monarch-common.js#L74

The better long term solution would be to have different functions for get and posting to this service.

**Comment by cmungall** [comment]
I believe this ticket can be closed. @kshefchek will you open a new ticket if one is required for any under-the-hood refactoring?

**Comment by cmungall** [comment]
we should also add a unit test for this
