### ISSUE TITLE
Standardize components and layout structure into Bootstrap 3 and compatible HTML/CSS

### ISSUE THREAD

**Issue by kltm** [monarch-initiative/monarch-legacy#542]
As it currently stands, many pages do not use BS3 layout and components to accomplish their tasks (e.g. #541). To help standardize the overall look and feel, people working on the actual interface should familiarize themselves with using BS3 for the interface and liberally apply it.

This will also greatly help when later on when (re)skinning the site to use CSS/theming.

This potentially touches on several other issues, such as: #543, #541, #518, #510, #489, and #430.

Progress was made on the base for this with completing #433.

**Comment by mellybelly** [comment]
Oops already closed.

**Comment by kltm** [comment]
@mellybelly you changed an open issue to a past release?

**Comment by mellybelly** [comment]
oops, fixed.

**Comment by nlwashington** [comment]
perhaps @DoctorBud knows if we have achieved this yet?  please reassign as necessary.

**Comment by jmcmurry** [comment]
@DoctorBud can we close?

**Comment by DoctorBud** [comment]
We are now using the latest (as of a month or so ago) BS3, and we can now use `.less` to customize the Bootstrap behavior via css/themes/monarch.less. We've also adopted the latest jQuery and jQueryUI, rather than the snapshotted versions we previously stored in our repo. We still have a lot of plain-old-CSS files, but that is not really a problem moving forward.

Closing this ticket.
