### ISSUE TITLE
Harmonize initialization of monarch app server and dependency management

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#597]
Things are a bit messy at the moment. Here is how things work
## Starting the server
- beta (tartini) is initiated from a Jenkins job, triggered on commits to master (start-server-dev.sh)
- stage and production are initiated from Bamboo, triggered by manual pushes (start-server-production.sh)

Jenkins currently uses an ugly and awkward daemonize command to run start-server. This has issues (see below)

Bamboo has recently switched to using supervisor. But we still need to check the details.
## Dependency management

Initially there were no dependencies other than ringo/stick (which rarely change), everything else was in the repo

We later made phenogrid an external dependency. We therefore updated the start-server scripts to run update_dependencies.sh, which performs the git operations necessary to pull from @monarch-initiative/phenogrid

ISSUE: this works for developers in their local environments, but it does _not_ work on tartini/jenkins, because of weird path hacking in the jenkins initiation. Untested on bamboo/{stage,prod}
## TODO
- switch to robust dependency management (e.g. npm)
- use supervisor for tartini setup too
- share supervisor scripts?

**Comment by cmungall** [comment]
Outcome of call:
- Larry will provide supervisor script in next day or two
- For this release we will check in phenogrid redundantly to monarch-app
  - @harryhoch I'll do this first time round
  - This is what we do with bbop.js anyway (cc @kltm)
  - For next release we'll use npm and integrate this with the bamboo/supervisor job

**Comment by harryhoch** [comment]
@cmungall, I'm ok with whatever you suggest, but I'm not sure what you mean by "check in phenogrid redundantly to monarch-app". Do you mean including the code in the repo? If so, do you have any advice for staying in sync? If not , can you clarify?

**Comment by cmungall** [comment]
Yes, I mean include the code in the repo. The intention was to push to stage today, so hopefully there should not need to be too many iterations of phenogrid releases before production (after which we can immediately switch to npm or bauer).

In the interim, the strategy would be for developers to recursively copy from their phenogrid repo into widgets/phenogrid on monarch, and commit.

For rapid development this is obviously sucky, something could be stitched with sym links on your dev machine.

**Comment by harryhoch** [comment]
hmm. that is going to be a bit tricky, I think we can make it work for a short time period. I'll add the code in...

**Comment by harryhoch** [comment]
@cmungall, I suggest that we should just develop any changes to phenogrid directly in the monarch-app repo until this is resolved, and then copy the code over to the phenogrid repo when done. Any objection?

**Comment by harryhoch** [comment]
@cmungall , @kltm, I'm just coming up to speed on details here. I think I might need some additional details to figure this one out. 

Regarding the "todo" items above
-    switch to robust dependency management (e.g. npm)
1. Any thoughts/preferences between tools? Based on a quick look, it seems like bower might be a bit more flexible than npm. 
2. what other dependencies should we be worrying about? Ideally, anything that we can get from a .git site, correct? This would include jquery, jqueryui, d3, and others? 

--    use supervisor for tartini setup too
  --  share supervisor scripts?

I'm not sure what you mean by "supervisor" is this a particular tool, or a jenkins/bamboo thing?

**Comment by kltm** [comment]
@harryhoch I have a pretty strong preference for npm for some of the stuff. While bower and npm fill very similar, but not exactly the same, niches at this point (although npm is taking over more of the functionality of bower), there are some technical advantages of npm (recursive dependency layout) that I think make it more suitable for complicated code. You'll end up with npm either way as you need it for bower; as well, there is a lot of tooling around npm (gulp, etc.) that will be helpful in general cleaning things up. A very clear explanation of the various ups and downs can be found here:

 http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging

The BBOP graph code will be split out, and there are dependencies on pup-tent and underscore as well. For the frontend, there will be dependencies on various amigo bits as well. For the backend, a dependency manager will be very helpful indeed since you'll be using node there.

Supervisor scripts are generic server spin-up and control code:

 http://supervisord.org/index.html

It's not amazing, but it is much much better than writing upstart/systemd jobs at this point.

We can talk more on Thursday if you want.

**Comment by harryhoch** [comment]
Thanks, @kltm, very helpful. I'll dig in. Probably best for a separate discussion if needed.

**Comment by harryhoch** [comment]
@kltm, having a bit more of a grasp of NPM, it seems to me that doing this right - i.e., putting a whole bunch of things under npm - is a non-trivial job involving substantial refactoring of the layout of the monarch-app code base. 

We could take various components like phenogrid, jquery, ringo, d3, etc., and just load them up via npm install from either npm registries or github sites, but then we'd have to rewire code to look for these components under node_modules, correct? 

Or am I missing an easier approach?

**Comment by kltm** [comment]
@harryhoch I don't think substantial refactoring, or much refactoring at all, would be necessary for using npm. Although it would be a different way in looking at/using the libraries you have. I think it's important to separate its two uses: library management for the server and asset (as well as library) management for the clients.

For the former case, the dependencies should be able to be handled just by using commonjs conventions and getting node_modules into the run path. Once (if) switched over to node, that part would become unnecessary.

For client libs, I think the extra bit that makes it nice is having something like gulp in the workflow to assemble (minimize, map, etc.) the assets for the JS clients' easy consumption in the application. If there is path wiring in the code, that's probably a problem that should be fixed sooner rather than later--libraries should be accessible or not via the environment.

We can talk a little about this on Thursday if you want, maybe with some examples in case I'm not understanding the issues at hand.

**Comment by harryhoch** [comment]
Thanks, @kltm. I think I must be missing something obvious. Let's try to discuss on Thursday

**Comment by harryhoch** [comment]
Took a stab at digging into this using gulp and npm to handle loading of ringo into environment for running of monarch-app. Didn't fare well - it looks like the npm ringo doesn't have the full-complement of files, including config/log4j.properties, which is needed.  Figured that trying to tweak the installation beyond what "npm install" would do would be to be subverting the point of going this route....

**Comment by kltm** [comment]
For this part, I'd leave the immediate ringojs issues to the side and worry about client/server libraries and workflow. If you can put this on ice for a little bit, I'll eventually have example code from another project that you could take a look at.

**Comment by harryhoch** [comment]
superseded by https://github.com/monarch-initiative/monarch-app/issues/665
