### ISSUE TITLE
add open source license 

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#636]
BSD? Apache? Is GPL going too far?

**Comment by selewis** [comment]
We (Berkeley) have to use a form of BSD as I recall from my last chat with
the legal types here

**Comment by harryhoch** [comment]
Do you have any examples of how you've used it in earlier projects?

**Comment by selewis** [comment]
I think this is it (it's BSD)

Copyright (c) 2010, Regents of the University of California.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

Neither the name of the Lawrence Berkeley National Lab nor the names of its
contributors may be used to endorse or promote products derived from this
software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE.

**Comment by harryhoch** [comment]
is there any reason not to add this to monarch-app as a license.txt file?

**Comment by kltm** [comment]
We have something similar for a lot of our software projects.

For example, in amigo in the LICENSE file at the top level (recommended location):

```
Copyright (c) 2012, Gene Ontology Consortium (http://geneontology.org)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Gene Ontology Consortium nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
```

Because of patent and reuse restrictions, we need to be able to redistribute under a 3-clause BSD license.

**Comment by harryhoch** [comment]
sounds reasonable. What should we substitute in for the copyright holder?

**Comment by jmcmurry** [comment]
Given that:
- LBL requires BSD-3
- OHSU is the prime institution
- There is a precedent for using a consortium (GO) rather than an institution (LBL) in the copyright

...My recommendation would be to use BSD-3 with the "Monarch Initiative" for the institution in Copyright per below. 

@cmungall @mellybelly
1. Is this OK with you?
2. If so, who (OHSU/LBL Tech transfer?) would I speak with to find out if this would be acceptable?
3. What is the desired year of copyright? 2014? 2015?

> Copyright (c) 2015, Monarch Initiative (monarchinitiative.org)
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by jgrethe** [comment]
Before speaking with Tech Transfer (based on a conversation I had with UCSD Tech Transfer) - look to see if a specific license was mentioned in the Data Sharing section of the proposal.  UC San Diego (don’t know if this has propagated to other UCs and affiliated institutions) views open source as open source with a non-commercial rider.  So may want to get any information/documentation that is meant to be be true open source (e.g. if BSD-3 was explicitly mentioned in the submitted proposal).  

Cheers,
Jeff

> On Jul 8, 2015, at 11:06 AM, Julie McMurry notifications@github.com wrote:
> 
> Given that:
> 
> LBL requires BSD-3
> OHSU is the prime institution
> There is a precedent for using a consortium (GO) rather than an institution (LBL) in the copyright My recommendation would be to use BSD-3 with the "Monarch Initiative" for the institution in Copyright per below. @cmungall https://github.com/cmungall @mellybelly https://github.com/mellybelly 1) Is this OK with you 2) If so, who (OHSU/LBL Tech transfer?) would I speak with to find out if this would be acceptable? 3) What is the desired year of copyright? 2014? 2015? ---------------------------- Copyright (c) 2015, Monarch Initiative. (http://monarchinitiative.org http://monarchinitiative.org/) All rights reserved.
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are met:
> 
> Redistributions of source code must retain the above copyright notice, this
> list of conditions and the following disclaimer.
> 
> Neither the name of the Monarch Initiative nor the names of its
> contributors may be used to endorse or promote products derived from this
> software without specific prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
> AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
> IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
> ARE DISCLAIMED.
> IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
> DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
> (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
> SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
> CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
> LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
> OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
> DAMAGE.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/monarch-initiative/monarch-app/issues/636#issuecomment-119680374.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu mailto:jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052 http://crbs.ucsd.edu/
http://www.linkedin.com/in/jgrethe http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by jmcmurry** [comment]
Hi Jeff, you bring up a good point re: proposal. If you could send the whole thing to me, I would be grateful as I don't yet have a copy. Cheers.

**Comment by jgrethe** [comment]
Melissa and Chris,
Since this went back and forth with NIH - can you forward the definitive data sharing plan that NIH has on record for this proposal.

Cheers,
Jeff

> On Jul 8, 2015, at 12:38 PM, Julie McMurry notifications@github.com wrote:
> 
> Hi Jeff, you bring up a good point re: proposal. If you could send the whole thing to me, I would be grateful as I don't yet have a copy. Cheers.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/monarch-initiative/monarch-app/issues/636#issuecomment-119708465.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu mailto:jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052 http://crbs.ucsd.edu/
http://www.linkedin.com/in/jgrethe http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by jmcmurry** [comment]
Melissa provided [three versions of the data sharing plan](https://docs.google.com/document/d/1pn1DhFpSPuMDQ0C22LZGOU13M7YTUfcZb94lNaJgqj0/edit)
- Funded first submission
- Unfunded second submission
- Renewal

The funded first submission states that we will use CC for code, but we are unlikely to be bound by this because:
- The intent was probably that data (not the code) be released under CC
- Appropriate **code** licenses (eg BSD) are still in the open source spirit of the plan

Neither the second submission nor the renewal states anything about a specific **code** license, just that it be "open source". @jgrethe I found [this documentation from UCSD](https://confluence.crbs.ucsd.edu/display/CRBS/Releasing+Open+Source+Software+at+UCSD) (excerpted below) which seems to indicate that BSD is the preferred path. What is the specific "non-commercial rider" that you had in mind? What is the critical path for moving this forward?

```
"There are several types of licenses available for open-source software release. 
UC San Diego will, to the extent possible, use the Berkeley Software Distribution (BSD) license 
because it does not have the restrictive, evolving nature that is inherent in GPL licenses. 
The latest proposed version of the GPL also conflicts with UC policies governing 
patents and copyrights."
```

**Comment by jgrethe** [comment]
Hi Julie,
My main reason for responding to the issue was a recent meeting I had with Tech Transfer at UCSD.  We had asked about a license for some other code (not related to MONARCH) and mentioned the one source requirement.  And we got a response that had no problem with the open source license except that it should be non-commercial. I specifically asked about this as open source (by its definition) wouldn’t allow this distinction and none of the licenses do.  But that didn’t really matter - the person we met with specifically mentioned that they don’t fully agree with the OSI definition of open source. Tech transfer did mention that if a specific license was required by the sponsor or had been agreed to (e.g. in the data sharing plan) - they would defer to that choice.  As I am not sure if LBNL has picked up similar policies (as they are affiliated with UC) - was just suggesting that you have documentation prior to a meeting with tech transfer in case this comes up…  Not sure what LBNL’s and OHSU’s stance on open source licenses is - but this last meeting with tech transfer down here made my head spin :)

Cheers,
Jeff

> On Jul 8, 2015, at 2:23 PM, Julie McMurry notifications@github.com wrote:
> 
> Melissa provided three versions of the data sharing plan https://docs.google.com/document/d/1pn1DhFpSPuMDQ0C22LZGOU13M7YTUfcZb94lNaJgqj0/edit
> Funded first submission
> Unfunded second submission
> Renewal
> The funded first submission states that we will use CC for code, but we are unlikely to be bound by this because:
> 
> The intent was probably that data (not the code) be released under CC
> Appropriate licenses (eg BSD) are still in the open source spirit of the plan
> Neither the second submission nor the renewal states anything about a specific license, just that it be "open source". @jgrethe https://github.com/jgrethe I found this documentation from UCSD https://confluence.crbs.ucsd.edu/display/CRBS/Releasing+Open+Source+Software+at+UCSD (excerpted below) which seems to indicate that BSD is the preferred path. What is the specific "non-commercial rider" that you had in mind? What is the critical path for moving this forward?
> 
> "There are several types of licenses available for open-source software release. 
> UC San Diego will, to the extent possible, use the Berkeley Software Distribution (BSD) license 
> because it does not have the restrictive, evolving nature that is inherent in GPL licenses. 
> The latest proposed version of the GPL also conflicts with UC policies governing 
> patents and copyrights."
> —
> Reply to this email directly or view it on GitHub https://github.com/monarch-initiative/monarch-app/issues/636#issuecomment-119734607.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu mailto:jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052 http://crbs.ucsd.edu/
http://www.linkedin.com/in/jgrethe http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.
