### ISSUE TITLE
can't find exocrine pancreatic insufficiency phenotype in autocomplete

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#647]
i am looking for the phenotype 'exocrine pancreatic insufficiency' in our system.
below is the screenshot i see when i try to autocomplete
![screen shot 2015-02-03 at 11 51 19 am](https://cloud.githubusercontent.com/assets/5124411/6028042/511a3afa-ab9b-11e4-9132-ef0e32b96ae4.png)
notice that these two things do not have "phenotype" as one of the categories.

now, you'll see that the term does exist, right here:
http://monarchinitiative.org/phenotype/HP:0001738
but i got to it in a roundabout way.

we need to figure out why this wasn't showing up in the autocomplete.

note that it does show up if i try to autocomplete for the synonym:
![screen shot 2015-02-03 at 11 54 19 am](https://cloud.githubusercontent.com/assets/5124411/6028081/9241ee74-ab9b-11e4-9109-89fd1a098090.png)

**Comment by kshefchek** [comment]
Confirmed that this does show up in scigraph autocomplete:
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/exocrine%20pancreatic%20in.json?limit=20&searchSynonyms=true&callback=fn

I think the issue here is some code that filters duplicates based on duplicate labels.  What should the behavior be here? I imagine what we want to do is only filter out duplicates of a single category.

**Comment by kshefchek** [comment]
Okay I take that back, looks like we do some checking to make sure we only filter out dupes within a single category, doing some debugging to see whats going wrong here.

**Comment by kshefchek** [comment]
This is fixed now.  I may have broken this when refactoring out the translation callbacks.
