### ISSUE TITLE
no phenogrid on model page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#649]
this is our example from the homepage:
http://monarchinitiative.org/model/MGI:3047228
it says there are no models (or diseases) on the compare tab.

**Comment by harryhoch** [comment]
Partially fixed by https://github.com/monarch-initiative/monarch-app/commit/c7584d839680aa04b2af06b910f39f8ae8fbfcb0.

Models have been set to redirect, but there was no handler for fetching a section of a model page. Turned app.get(/genotype/:id/:section.:fmt? ... into a fetchGenotypeSection procedure, and added a similar call for fetching the section of a model page.

However, this runs into trouble when  we do a scigraph call:

not found: http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/MGI:3047228.json
FETCHING: http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/MGI:3047228.json data={"depth":1}
RESULT: [object Object]
STATUS: 404
not found: http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/MGI:3047228.json
TypeError: Cannot read property "0.0" from undefined
    at lib/monarch/api.js:5692 (anonymous)
    at lib/monarch/api.js:6800 (anonymous)

now, that may be a scigraph error, but I'm also not sure - should fetchClassInfo be modified to better handle a null result from getGraphNeighbors()? Thoughts?

**Comment by kshefchek** [comment]
Fixed with b7ac7bc6610a937c161cb2dadbd29c7f230479ba
