### ISSUE TITLE
Duplicate Digeorge syndrome subclasses

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#66]
Digeorge syndrome
http://tartini.crbs.ucsd.edu/disease/OMIM_188400

is listed as having two identical subclasses, which reroute to this page when clicked.

so, are they subclasses or equivalent?

**Comment by mellybelly** [comment]
So I think this is a problem with the way the equivalent classes are being displayed and/or resolved. 
http://purl.obolibrary.org/obo/OMIM_188400 is declared equivalentTo
http://purl.obolibrary.org/obo/DOID_11198
in the ontology.

However, in the app, the resolution of both the subclasses is to 
http://tartini.crbs.ucsd.edu/disease/DOID_11198, which is the same as the parent page as you noted.

Note I have seen other cases where there are actually two subclasses, but they are real because they are missing any equivalency axioms.

**Comment by pnrobinson** [comment]
In this particular case, the nosology is rather complicated. The main disease should be 22q11.2 deletion syndrome, and historically there were a number of other designations such as di George, that describe clinical variants that some individuals with this deletion get (i.e., not all people with deletion 22q11 get the clinical picture of DiGeorge syndrome).
The Wikipedia article is pretty good:
http://en.wikipedia.org/wiki/DiGeorge_syndrome

I realise this wasn't the original topic of this thread, but I am taking the opportunity to mention this. By using the Orphanet rare disease ontology, we would get the name that is preferred in the community:

http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=126&Disease_Disease_Search_diseaseGroup=DiGeorge-syndrome&Disease_Disease_Search_diseaseType=Pat&Disease%28s%29/group%20of%20diseases=Monosomy-22q11--DiGeorge-syndrome-&title=Monosomy-22q11--DiGeorge-syndrome-&search=Disease_Search_Simple

Orphanet lists all of the clinical variants as synonyms, which is not really true. I believe that the community now recommends using just the term "22q11.2 deletion syndrome", and the other terms are regarded as obsolete.

-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson

---

Von: Melissa Haendel [notifications@github.com]
Gesendet: Sonntag, 26. Januar 2014 01:15
An: monarch-initiative/monarch-app
Betreff: Re: [monarch-app] Duplicate Digeorge syndrome subclasses (#66)

So I think this is a problem with the way the equivalent classes are being displayed and/or resolved.
http://purl.obolibrary.org/obo/OMIM_188400 is declared equivalentTo
http://purl.obolibrary.org/obo/DOID_11198
in the ontology.

However, in the app, the resolution of both the subclasses is to
http://tartini.crbs.ucsd.edu/disease/DOID_11198, which is the same as the parent page as you noted.

Note I have seen other cases where there are actually two subclasses, but they are real because they are missing any equivalency axioms.

**Comment by cmungall** [comment]
This is all a consequence of the bug in OntoQuest that Jing is fixing

Whenever you query ontoquest using an OMIM class that has an equivalent DO class, it gives you back the result of a query on the DO class. See:
- http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/rel/all/OMIM_188400
- http://nif-services-stage.neuinfo.org//ontoquest-lamhdi/concepts/term/OMIM_188400

This violates assumptions made by webapp.js, giving rise to subsequent weirdness.

**Comment by cmungall** [comment]
here's how it looks in Protege, as intended. Note that Protege doesn't show the URI of the focus class, but here it is OMIM_188400

![screen shot 2014-01-26 at 1 20 27 pm](https://f.cloud.github.com/assets/50745/2005086/b642db86-86cf-11e3-9ea1-717446ffaa1d.png)

**Comment by nlwashington** [comment]
In that screenshot, why are there two labels:

"DiGeorge syndrome = DOID_11198" and 
"DOID_11198 = DiGeorge syndrome"  ?

Are they different things?

Nicole

**Comment by mellybelly** [comment]
They are http://purl.obolibrary.org/obo/OMIM_188400 and
http://purl.obolibrary.org/obo/DOID_11198
which are equivalent. you can see the ID at the bottom of the screen when you hover to tell you if it is a duplicate display or two different things.

**Comment by harryhoch** [comment]
will be fixed with https://github.com/monarch-initiative/monarch-app/issues/180
