### ISSUE TITLE
Update search and compare descriptions on /labs/analyze page

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#674]
Per @harryhoch, we need to clarify this, @mellybelly @nlwashington @cmungall suggestions?

**Comment by kshefchek** [comment]
Some thoughts from the call on what's currently on the site:
Search: Search for phenotypically similar genes, genotypes, and diseases 
Compare: Compare phenotype profile against a set of genes

**Comment by nlwashington** [comment]
Jumbotron:
The Phenotype Analysis tool enables you search our database for human diseases, or animal model genes for those with similar phenotype profiles, or visualize phenotypic comparison output from Exomiser.    (with the above, can you add a link to the upload tab for the “visualize” word?)  (also link to exomiser: http://www.sanger.ac.uk/resources/software/exomiser/submit/)

Search:
In the main search window, above the boxes add:
Instructions:  You can use this tool to identify phenotypically similar diseases or genes in a variety of organisms.  We use an OwlSim (link) Semantic Similarity analysis engine to compare the set of phenotypes (we call a Phenotypic Profile) you enter below for your query in two ways: either against the entire database (search) or to a selected set of genes (compare).  The results will show up in the Results tab. (If you want to visualize preformatted Exomiser output, jump over to the “Upload” (link) tab.)  The list of phenotypes and genes stay populated enabling you to iterate and refine your lists.  You can start over by hitting the Reset button.  If you want to understand more how this works, please read more on our About page (link)

Example 1:  Select four phenotypes such as A, B, C, D.  Then, select to search against mouse.  Click submit and go! 
Example 2:  Select the same four phenotypes.  Then select to compare the profile against genes P, Q, R.  
(i will work on these examples, or you can fill in known good ones)

For the Phenotype box:
instead of “add to search list”, maybe say:
“Step 1.  Create a phenotype profile:”
with subtext that says:
Select one or more phenotypes by using the autocomplete.  Each will get added to a list at the bottom of the section.

For the Settings box:
Search:
Refine your search space by taxon or target type (disease or gene).

Compare:
i would move the language that’s under the “Gene IDs” up to the top, and remove any redundant-seeming text with:

“Enter a specific set of genes to compare their phenotypes against to your query.  Select them using either the autocomplete, or enter IDs directly using the text box (or a combination of both).  You can expand your list of genes using the convenience buttons at the bottom.”

Upload:
If you have a phenotype-comparison formatted JSON file, you can visualize it with our grid by uploading or pasting the contents below.  We provide several examples for you to play with. 

The Exomiser (https://www.sanger.ac.uk/resources/software/exomiser/) is a Java program that functionally annotates variants from whole-exome sequencing data starting from a VCF file, and leverages variant frequency, pathogenicity, quality, inheritance pattern, and model organism phenotype data.  Coming soon, you will be able to visualize the results from an Exomiser analysis with our grid.  To be included with Exomiser 7.0, you will be able to export a phenogrid-ready file to display here.  Stay tuned for updates. 

i will be refining the examples to use this weekend for the workshop.  i would like a few.  ideally i would like some accompanying text to explain each on the page.

**Comment by kshefchek** [comment]
Some notes from @kltm:
- disable the submit button until someone enters a phenotype
- dim font for compare settings when search is active, and vice versa when selecting the compare radio button
- move instructions out of jumbotron, perhaps have this link to another page, or have some hide/show functionality (@nlwashington thoughts?)

**Comment by nlwashington** [comment]
if we can do something schnazzy where we show the instructions in the jumbotron upon first viewing, and then save state so that upon return if the user has last wanted it hidden, it remembers.  is that possible?

**Comment by kltm** [comment]
No, not without adding state/sessions to the system.

I don't thing the jumbotron is the right place for instructions since 1) it pushes the activity lower and the activity already has instructions in it and 2) it's the jumbotron.

**Comment by kltm** [comment]
It might be easier to lead the user through the process with the inline instructions and intelligent highlighting (I think @kshefchek has committed some of that). Also, examples of intended input in the boxes "placeholder" property can also be used to direct users.

**Comment by nlwashington** [comment]
i agree that the activity is way too low on the page, but felt that we needed better explanation (sooner) about what to do.  i experimented and put it originally in the respective tabs for the functionality, but it also pushed it lower, and i didn't like that either. (and with that method, if you scrolled down to the functional part, then the tabs moved too high.)  i hadn't found a good solution yet.  maybe you guys will.

**Comment by harryhoch** [comment]
I’m with @kltm. I have some ideas of how we might do this. Perhaps something to discuss at our Thursday meeting?

On Mar 26, 2015, at 7:49 PM, Kent Shefchek <notifications@github.com<mailto:notifications@github.com>> wrote:

i agree that the activity is way too low on the page, but felt that we needed better explanation (sooner) about what to do. i experimented and put it originally in the respective tabs for the functionality, but it also pushed it lower, and i didn't like that either. (and with that method, if you scrolled down to the functional part, then the tabs moved too high.) i hadn't found a good solution yet. maybe you guys will.

—
Reply to this email directly or view it on GitHubhttps://github.com/monarch-initiative/monarch-app/issues/674#issuecomment-86756070.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics
harryh@pitt.edumailto:harryh@pitt.edu  412 648 9300

**Comment by kshefchek** [comment]
Closing in favor of more specific #783
