### ISSUE TITLE
Configure golr widget for Monarch

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#687]
This is a continuation of #678

We now have a partial pipeline in place between SG and Golr, generic widget visible here and 'Disease-golr'

http://tartini.crbs.ucsd.edu/labs/widget-scratch/phenotype/HP:0008065

Some next steps, not necessarily in order:
- load additional associations, e.g mouse gene/genotype2p; gene2disease; coordinate with @ccondit 
  - once we do this we will want to start filling in the subject/object category fields
- Figure out why object is not hyperlinked, coordinate with @kltm 
- We want OMIM links etc to be local. This is a generic setting, check with @kltm
- Fix evidence
- Fix CSS and experiment with different layout options 
- Your Ideas Here...
-

**Comment by cmungall** [comment]
Note: all this is in labs and can be conducted on master. After a period of development we will add to existing pages in which case a branch would be prudent

**Comment by cmungall** [comment]
Just to experiment, I added a disease page:
http://tartini.crbs.ucsd.edu/labs/widget-scratch/disease/DOID:14330

**Comment by kltm** [comment]
(I wish there was a way to thread,)

``` text
Figure out why object is not hyperlinked, coordinate with @kltm 
```

I'm 95% certain that this is due to the linker not having the information needed. If you're using amigo resources, you need to make sure everything is in go-dbxrefs.yaml and that you are using a recent amigo2.js file as the linker resource.

``` text
We want OMIM links etc to be local. This is a generic setting, check with @kltm 
```

This too is a linker data issue. It might be best just to get familiar with the linker API and use your own data. Or you could use the "handler" API to override the display in various fields. It might be best to have a review of what's available with @kshefchek at some point.

**Comment by cmungall** [comment]
Can you point to the linker API docs?

**Comment by kltm** [comment]
The main ones are:

 https://kltm.github.io/bbop-js/docs/files/linker-js.html
 https://kltm.github.io/amigo/javascript/docs/files/linker-js.html

And the amigo tests:

 https://github.com/geneontology/amigo/blob/master/javascript/lib/amigo/linker.js.tests

The important thing is 1) some of the widgets take a "linker" object as an argument (e.g. the results table widget) and 2) a "linker" object is anything that duck types to the described linker API. Behind that, you can put any kind of craziness that you want. A concrete example of this is the degenerately minimal BBOP-JS description of the API versus the AmiGO implementation:

 https://github.com/berkeleybop/bbop-js/blob/master/lib/bbop/linker.js
 https://github.com/geneontology/amigo/blob/master/javascript/lib/amigo/linker.js

**Comment by kshefchek** [comment]
A little late to the party, starting work on fixing links:

As @kltm mentioned, we're not seeing links for HP terms because the amigo.data.xrefs object does not contain this mapping.  Which leads to:

Do we want to use the go-dbxrefs.yaml file as a configuration file for links?  Instead, we can use the internal monarch file in conf/xrefs.json, but I would say the majority of links in these tables will be to internal pages.  This should be straightforward, with the exception of OMIM where we need to link to either gene or disease pages.  @kltm since we are using the generic "subject, object, evidence, etc." (see [conf file](https://github.com/monarch-initiative/monarch-app/blob/05139b077226591de205575686f4f71d68cac82b/conf/golr-conf.json)) I'm thinking it may be best to break this out into a new linker class as I don't see much reuse with amigo here - or am I misinterpreting how this all fits together?

**Comment by kltm** [comment]
@kshefchek Because of the internal routing that you need to do (and because you are not literally an instance of AmiGO), you are unlikely to be able to use the amigo class directly, no matter what data you feed it. That said, I suspect that using it as your base would be very close.

The linker takes an id, and often a second (or third), argument. Starting there, it determines whether or not the id is "external"--in which case it basically uses the processed xrefs file as a lookup--or "internal"--in which case it does whatever it needs to do to make the internal link to the correct location.

**Comment by kltm** [comment]
@cmungall, question about IDs and links. Let's say OMIM:G is a gene and OMIM:D is a disease. Do we need to be able to route these differently within Monarch depending on the (subject|object)_category? Or is this an issue upstream (i.e. they should actually have different namespaces) and this is not really our problem?

**Comment by kltm** [comment]
@kshefchek honestly, the more I look at the code, the more I see that decisions were made with the assumption that URLs can be routed with just ID and field names, without looking elsewhere in the document for contextual information. Maybe we should touch bases with @cmungall one more times to make sure that this is the best way to go for long-term development.

If not, the ability to access the larger context could (and maybe should) be added to bbop-js functions to increase the general applicability; however, it would be an incompatible (although not earth shaking) API break. I think it would then be best handled by 1) allowing the _process_entry function to be overridden and/or 2) making the handler dispatch pass more information by default.

**Comment by kshefchek** [comment]
@kltm, looking a the data I still suspect that will need to disambiguate a prefix with it's categorical information.  For example MGI: can be either a gene or genotype:

Gene:
http://duckworth.crbs.ucsd.edu:9000/scigraph/graph/MGI:1314873

Genotype:
http://duckworth.crbs.ucsd.edu:9000/scigraph/graph/MGI:2166376

But I agree on getting the official word from @cmungall before putting any time into updating the bbop, especially if it will break things.  In the meantime I'll take a look at your suggestions.

**Comment by cmungall** [comment]
I got distracted by the OMIM gene-vs-disease issue. There are other cases where the ID is insufficient in itself to determine what kind of page to link to. The category is necessary and sufficient for directing to specific monarch pages. It would be most efficient to do this client side, as the category should already be known to the widget.

It would be possible to have a routing page /object/:id that looks up the category and then redirects. We may want this anyway but I think we should try to avoid the indirection.

A more radical strategy is to do away with the concept of categories at the page logic level. All pages could be /object/:id -- a lot of the functionality is and will be shared. But we don't need to move towards this yet.

**Comment by kshefchek** [comment]
Grabbing the _category property is pretty easy, it just requires some tweaks to the bbop.widget code.  There is a short term more hacky solution to either override one of the private functions in the bbop.widget.display code, but @kltm has scoped out a better long term solution.

**Comment by kshefchek** [comment]
Internal links are fixed, will track the bbop issue and touch things up when that is finished.

**Comment by kltm** [comment]
@kshefchek are you using the linker for this, or some other mechanism?

**Comment by kshefchek** [comment]
I just added this to _process_entry():

```
    var category = golr_resp.get_doc_field(did, fid+'_category');
    var ilink = linker.anchor({id: iid, label: ilabel, hilite: hl, category: category}, fid);
```

And updated the linker accordingly

**Comment by kltm** [comment]
Fair enough. Do you have some unit tests for your linker?

I'm almost done the fox for the code at the BBOP end...

**Comment by kshefchek** [comment]
unit tests coming, should I write them with behave or something like you're doing with mr t.

**Comment by kltm** [comment]
Possibly, but for something low-level like demonstrating how the linker works (and proving that it does as expected) it's not really necessary. It might be nice to use Mocha or something similar. I'll see what I can scare up, but anything in a separate runnable file is a good start.

I've added the override function to bbop-js in the most recent version (bbop@2.3.1). You can get at it anywhere along the lines of:

``` js
var results = new bbop.widget.live_results('results', search, confc, handler, linker, results_opts);
bbop.widget.display.results_table_by_class_conf_b3.prototype.process_entry = function(){
  return 'foo';
};
```

(which naturally makes all cell entries "foo")

**Comment by kshefchek** [comment]
Updated to the above method in 308c73afcaaaae1ab8a4e95a9e54e7c261791e2a

**Comment by kltm** [comment]
@kshefchek the diff looks right to me--did that change make sense to you?

**Comment by kshefchek** [comment]
Yes that update works for me.  Before I had copied the live_results and widgets.display class into the monarch repo just to access that function (8e0f1462bc32152ce0f17f2e4c1b36190beaa533), so this is much improved, thanks for the quick update!

**Comment by kshefchek** [comment]
At this point I'm ready to add additional associations:

```
    load additional associations, e.g mouse gene/genotype2p; gene2disease; coordinate with @ccondit 
    once we do this we will want to start filling in the subject/object category fields
```

@ccondit is golr currently set up to handle additional queries?
