### ISSUE TITLE
Ensure site works behind firewalls

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#753]
Continued from #751 

Some external sites may have problems with client side js accessing non-80 servers. cc @kltm

**Comment by kltm** [comment]
A specific use case that people often run into is that when visiting a campus, the wireless network blocks anything not going over the two usual ports for HTTP and HTTPS (80 and 443). Since Monarch is now using GOlr widgets, where the JS collects data on its own, these data services need to be made available as their own (sub)domains on these ports.

For example, a possible solution would be for Solr to be available on solr-production.monarchinitiative.org:80/443, etc.

**Comment by kshefchek** [comment]
cc @llui and @ccondit, would it be possible to move SciGraph to port 80 and Golr to 443 on each server for Monarch or would this pose any issues?

**Comment by kltm** [comment]
Why would GOlr be on 443?

**Comment by kltm** [comment]
Ah, if you're trying to get them working on the same machine, the cleanest way would be to use a CNAME. You should not mix protocols just to try and get around naming issues.

**Comment by ccondit** [comment]
Yes - renaming would be better. And I doubt that Larry will want to use privileged ports.

**Comment by llui** [comment]
Yes the best way to resolve this is to create CNAME's for each service you want to expose via port 80.  After that, I can make the apache proxy configuration changes to point to the correct backend service.

**Comment by kshefchek** [comment]
Also see #966, would it be possible to set this up?

**Comment by DoctorBud** [comment]
I think this issue is closable. Production monarch uses port 80 for all of its services at this time.

**Comment by llui** [comment]
Please unsubscribe llui@ncmir.ucsd.edu

## 

Vicky Rowley

IT Manager
Center for Research in Biological Systems, and the
National Center for Microscopy and Imaging Research

University of California, San Diego
9500 Gilman Dr. MC0608
La Jolla, CA 92093-0608
(858) 822-0708 office
vrowley@ucsd.edu
