### ISSUE TITLE
Add a tsv download button to tables

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#758]
E.g. on http://beta.monarchinitiative.org/Phenotype/HP:0001638#genes

We should be able to go get the gene association list easily

the download button already exists in the bbop widget, just need to customize

We should also have json-ld downloads too, but later

**Comment by kshefchek** [comment]
Also see #80 and #477

**Comment by kshefchek** [comment]
@kltm any chance you've worked on a bootstrap equivalent to the tsv export jquery widget?

**Comment by kltm** [comment]
TSV should be available directly from the manager if you already know the fields. If you want dynamic fields, you can see how the download button of the AmiGO page works:

 http://amigo.geneontology.org/amigo/search/bioentity

And look for references to "bio_flex_download_button" in LiveSearchGOlr.js. It is a fairly primitive system all said, and could be done cleaner with the new manager system (rather then being tied so deeply to the old manager). It is based on the simple drag-and-drop system available in jquery-ui.

While it is driven

**Comment by kshefchek** [comment]
I've added a tsv download button to all the tables.  It should generate a tsv format for the filters currently set on the table.  The max is set to 100k but we can increase this.

Right now it forwards to the golr URL and displays the data on a web page rather than generating a download box.  Is this something I need to fix or is something we can set on the server, cc @ccondit and @kltm

**Comment by kshefchek** [comment]
In testing it seems this something we'll likely need to configure with the golr server (ie configuring the Content-Disposition for tsv files) or just live with.  I've tried changing the button to an anchor element and adding the download attribute but this doesn't seem to work reliably as it's only supported in Chrome.
