### ISSUE TITLE
Phenogrid error on DOID:1612

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#806]
I'm getting the following error on http://beta.monarchinitiative.org/disease/DOID:1612 : 

```
    TypeError: item.taxon is undefined
    ...": item.label, "species": species, "taxon": item.taxon.id, "type": type, "pos": ...
    phenogrid.js (line 1157, col 58)
```

These errors seem to take out the rest of our client side scripts, and therefore none of the tabs will load.  Will break that out into new issue.

**Comment by harryhoch** [comment]
@yuanzhou, please look into this and let me know if you're not sure how to proceed.

**Comment by yuanzhou** [comment]
Bug fixed! It was caused due to missing taxon object when the dummy item was created in `_padSpeciesData()`. In the overvoew mode, three species are compared, sometimes for example fish doesn't have enough returned data, but the grid view is created based on 10 data cells of each species, that's why dummy data needs to be created to fill in the empty space. Thanks a lot to Mike @davism84 he spent time helping me understand the background knowledge and walk through this bug and found the reason.
