### ISSUE TITLE
Any errors in phenogrid.js kill all client side js

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#807]
See #806 as an example

This is the cause for data tabs to be stuck on "Pending..."

I believe we can fix this by ordering all client side scripts in a single Jquery document.ready function using puptent.

**Comment by yuanzhou** [comment]
Sorry I didn't notice this error this afternoon. I just bundled all phenogrid js files into one phenogrid.js and all css files into one phenogrid.css. Also updated the code in webapp.js. 

I think the bundled single file makes it lots easier to integrate with monarch-app, and easier for debugging.

Couldn't test it on beta.monarchinitiative.org due to a 503 error. Will look into this tomorrow.

**Comment by kshefchek** [comment]
This has been happening for a little while now, see https://github.com/monarch-initiative/monarch-app/issues/720#issuecomment-109355054 so it is not the result of any recent changes but rather how we're organizing the client side code.

**Comment by yuanzhou** [comment]
@kshefchek I've fixed the #806
