### ISSUE TITLE
Fix phenogrid ajax spinner on analyze and data pages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#813]
It looks like the ajax-cube css spinner is no longer working when the phenogrid is loading on the analyze page and any of the data pages, see http://beta.monarchinitiative.org/disease/DOID:14330 as an example.

It is possible I broke something with this commit https://github.com/monarch-initiative/monarch-app/commit/1b2d5bce391296e1e95fd0a3eb01af4af8242442#diff-4137b7da4611209617f9d9f002105b7f

**Comment by yuanzhou** [comment]
Yes, I actually removed that spinner loading last week since it can be replaced with a better/simpler design with font-awesome loading icon. Will add that later.

But I don't think this change will affect monarch-app.

**Comment by kshefchek** [comment]
@yuanzhou thanks!

**Comment by DoctorBud** [comment]
I think we have a better handle on the image loading than we did a week ago (yay, imagePath:), so putting the spinner back shouldn't be too much trouble if we want that.

**Comment by yuanzhou** [comment]
I'll be working on this loading indicator. Will use font awesome loading image.

**Comment by yuanzhou** [comment]
Loading spinner was added to phenogrid using font awesome animated loading font icon. Without introducing new external images and no extra CSS. But I couldn't test this out on Monarch-App site, http://beta.monarchinitiative.org/disease/OMIM:105830 outputs 500 server error. I also got this error page at http://beta.monarchinitiative.org/analyze/phenotypes/?input_items=MP%3A0001399+HP%3A0006801&mode=search&target_species=all&limit=100
@harryhoch  @kshefchek I'll close this issue once the beta server is back working.

**Comment by kshefchek** [comment]
Could we also add the spinner when fetching the phenotype list from the monarch server?

**Comment by harryhoch** [comment]
@yuanzhou, please take a look.

**Comment by yuanzhou** [comment]
@kshefchek @harryhoch I think I referred this in issue #862, basically it's on the monarch-app's end, not phenogrid. It's best to use that blue image loader since it's used for all other tabs. If you take a look at `js/phenogridloader-no-species.js` for example, the `phenotype_list` array is assigned to phenogrid via `phenotypeData` option once all the phenotypes are loaded. There's no way I can add a spinner before phenogrid gets called. 

@kshefchek for the disease page, I think you can add that blue image spinner somewhere before the ajax call returns the data. In `js/Analyze.js` it seems the data is loaded differently.

**Comment by kshefchek** [comment]
This is doable, I wasn't sure if we wanted a single ajax loader for the two calls.

**Comment by yuanzhou** [comment]
@kshefchek FYI, after @harryhoch changed the sync ajax calls to async, the phenogrid loading spinner shows up everytime before the content is fully loaded. So I guess this resolved this issue too.
