### ISSUE TITLE
Migrate monarch-app to node.js

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#817]
Switch from ringo to node

Previously the blocker here was the switch from sync to async calls. The initial implementation made multiple sync service calls in serial - switching the logic to async would have been a nightmare. Now the majority of service calls are async and in the client (e.g. golr widgets) so this would presumably be much easier.

This will not happen before the release (obviously) but am open to discussion of timing of experimental branches etc. Comments welcome under this ticket. Discussions of other options welcome, but it's unlikely we'll be using grails... 

cc

@harryhoch 
@jnguyenx 
@kltm 
@kshefchek 
@DoctorBud
@nathandunn 
@nlwashington

**Comment by harryhoch** [comment]
I have no particular experience with node.js, and I'm not the one with my hands deep in the code, but I keep hoping for something that is note quite so wild-west as JavaScript.   

I have no idea regarding the validity of any of the content of this article, but it certainly makes me want to take a closer look -- https://developerblog.redhat.com/2015/04/22/scala-vs-node-js-as-a-restful-backend-server/

**Comment by kltm** [comment]
I think the transparent reuse of client and server code is a big win. I'd think that if somebody was dead set against the current JS, starting the migration to ES6 sooner might be a good way to go.

That said, I think there probably isn't too big a jump that needs to be in the server, especially now that a lot of the old API weirdness is apparently being eliminated. Before anything drastic like switching languages, it's probably worth just teasing out the remote service call bits and seeing how many pain points actually exist.

**Comment by nathandunn** [comment]
As much as I always advocate Grails (JVM + closures + niceties + web-framework + ORM [optional]), I think that node.js might be the easiest jump.     Not because the client / server re-use (I’ve done this with both JS and Java, and I always feel like the payoff is moderate relative to other things), but because most of what the middle-layer does is routing / templating, which node/express is very good at and requires almost no changes to the front-end mustache pages.    Grails has a very similar routing framework (it can use mustache, but defaults eg. jsp / velocity / freemarker).   

The scala / play framework or clojure / wicket (or maybe something else) might be a good functional java alternative if that is important.   But the way the server is built / is moving, it appears to be going more in the direction of light middle-ware with the GOLR layer doing most of the heavy-lifting.  

I think my only caveats would be:
1 - do you need JVM integration (ontology libraries, etc) . . . then I would migrate to one of the other JVM frameworks? 
2 - who is going to be writing / maintaining it?  

In the long-run it probably doesn’t matter so long as the chosen library is well supported / maintained (any of the above will do this).  

Nathan

**Comment by harryhoch** [comment]
@nathandunn,   your analysis makes sense to me. In the case of Exomiser, we discussed JVM-like integration (very possible with Ringo) and opted for a REST interface instead. If we're ok with that pattern, node will probably make sense....

as much as I'd love something functional-ish, it doesn't seem particularly warranted here...

**Comment by cmungall** [comment]
This is a good summary.

There will be an increasing role in Monarch for application logic 
written in a JVM language, interfacing directly with SG, OWLAPI, machine 
learning APIs, etc. But this logic will be outside of monarch-app, which 
already transitioned to a lightweight template server with most UI on 
the client side.

**Comment by kltm** [comment]
Elsewhere, we've been migrating our data libraries to something more usable (https://github.com/berkeleybop/bbop-rest-manager; supporting synchronous, callback, and promises) and have had good luck with some of the /synchronous/ http clients in node. Although the one we're using does a very hard lockup, it would probably work fine on a properly configured backend.

From previous poking around all the libs are available on npm, and since we could start out with a synchronous http lib to simulate the current setup, this means that a switch to node is pretty much trivial for anybody with a free afternoon.

**Comment by DoctorBud** [comment]
I've made progress on this at https://github.com/monarch-initiative/monarch-app/pull/914.

The immediate goal is to have a single body of source code that can operate as either a RingoJS or a NodeJS server, where the tests successfully complete in both environments. Currently, the NodeJS is between 25-50% complete.

Once we have feature parity and tests pass in both environments, we will deprecate the use of RingoJS (but still maintain it until we have verified there are no gotchas in terms of NodeJS running on a production machine) and switch the various startup scripts and makefiles to use NodeJS.

**Comment by DoctorBud** [comment]
Current status:
- Home Page loads
- Blog feed lookup works and fills in the Blog area of the home page
- Disease page doesn't work, but successfully makes the first of its outbound http requests to a data source. I'm using the npm sync-request module to manage the outbound connection, which helps avoid writing async versions of the data fetching.
- I'm using https://github.com/Leonidas-from-XIV/node-xml2js as the XML parser alternative to RingoJS' builtin XML parser. There are some differences in behavior, but I have found a way to adapt code from one to the other.

Next Steps:
- Complete the Disease landing page so that it works and loads the bar chart
- Apply the same technique to the other landing pages (using sync-request)

Next Next Steps:
- Write an adaptor that enables parameterized URLs to work both with Ringo's Stick and with NodeJS's HAPI HTTP servers. This should let us go to particular Disease pages  (or Genotype etc).

Current Tech:

I've adopted some particular NodeJS libraries to replace some of the libraries that only exist in RingoJS with ones that can be used in NodeJS. The particular versions and libraries here are not cast in stone; there may be better alternatives as we move forward (hooray for choice!).
- NodeJS (v0.12.7)
- HAPI.js as HTTP server http://hapijs.com
- xml2pdf as XML Parser https://github.com/Leonidas-from-XIV/node-xml2js
- sync-request as a replacement for Ringo's httpclient  https://github.com/ForbesLindesay/sync-request

**Comment by cmungall** [comment]
I just realized we had a lot more cruft than I thought in api.js; none of the calls to ontoquest, federation are needed. All this means is that you may have ported more than you need to. I would like to decruft soon, but don't want to make future merges hard. No action needed at this point, just FYI

**Comment by cmungall** [comment]
Done

cruft ticket here: #975
