### ISSUE TITLE
Implement Compare Tab for Phenotype pages

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#819]
For consideration: As the phenogrid is the showcase element, it could be nice to display it also in situations where you have only one phenotype. Even though it is a sparse matrix, it could whet the appetite for more complex analyses. This is related to #818 because the compare tab can not be the default one unless there are no edge cases where it doesn't appear at all. Please advise. 

I go to http://beta.monarchinitiative.org/phenotype/HP:0001438
and the tabs include the "Compare" tab

**Comment by harryhoch** [comment]
let's discuss. I'm not sure what to make of this idea.

**Comment by kshefchek** [comment]
I think the issue is that the overview tab often has very little content, especially on non-disease and phenotype pages.  Since owlsim/phenogrid is what sets us apart it could be nice to put this front and center.  Another thought is that I can add 1-2 barcharts of the data once I have the dynamic widget ready which should be a couple of days.  But even so, the barcharts are just barcharts and we need to get people to the phenogrid.  We could instead have a message along with a screenshot that links to the tab.

**Comment by harryhoch** [comment]
Suggest that we think about this in the context of a broader reconsideration of the overview page...

**Comment by kshefchek** [comment]
Okay I think we will leave things as is for now, perhaps we can incorporate some barcharts in the overview tab if I can get it to work in the next couple of days.
