### ISSUE TITLE
Compare function API error

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#866]
See: http://beta.monarchinitiative.org/compare/MP:0001399/NCBIGene:5625,ZFIN:ZDB-GENE-101116-1,ZFIN:ZDB-GENE-041008-73,ZFIN:ZDB-GENE-120215-75,ENSEMBL:ENSDARG00000086512,MGI:97770

Error: Cannot read property "id" from undefined

The function is also using NIF which may be part of the issue.

**Comment by kshefchek** [comment]
See comment here: https://github.com/monarch-initiative/monarch-app/issues/644#issuecomment-146639283

When grouping targets with a plus sign the call fails. When listing with a comma the call will work.

This issue is this line: https://github.com/monarch-initiative/monarch-app/blob/9bcc462c/lib/monarch/api.js#L4329 where we concatenate any IDs with a plus sign and send this to scigraph. This will return an empty graph from scigraph and result in the rest of code failing.

@nlwashington what is the intended behavior when grouping targets with a plus sign? Any chance you could point me to a commit when this code was working?

**Comment by nlwashington** [comment]
so, for this example.
these have no phenotypes:
ZFIN:ZDB-GENE-101116-1
ZFIN:ZDB-GENE-041008-73
ZFIN:ZDB-GENE-120215-75
ENSEMBL:ENSDARG00000086512

MGI:97770 does have phenotypes:
HP:0004325,HP:0009887,MP:0005332,MP:0003131,HP:0003112,MP:0001488

but no result is returned from owlsim.  i believe this is because there is nothing that is comparable between them.  note, if i add the mp term that is part of the query into the list of phenotypes that is the resulting call for owlsim directly, it does return just a single LCS for the set.  

note that this is likely because owlsim has an internal cutoff for performance reasons.

so, this begs the question, what should be the correct behavior here?  options...
1.  owlsim should return everything (make the default cutoff 0.0)
2.  leave owlsim alone, and the monarch comparison wrapper should add a list of zero comparison results, and a score of zero to the list, so that every query item appears in the resulting list.
3.  leave this alone, which means that some of the query items will not appear in the resulting list.

**Comment by nlwashington** [comment]
cc @cmungall

**Comment by nlwashington** [comment]
note, here is the resulting owlsim call that is made for the MGI gene above:
http://owlsim.monarchinitiative.org/compareAttributeSets?a=MP:0001399&b=HP:0004325&b=HP:0009887&b=MP:0005332&b=MP:0003131&b=HP:0003112&b=MP:0001488

**Comment by jmcmurry** [comment]
@kshefchek any update on this? What is needed to close?

**Comment by kshefchek** [comment]
Let's get the final word from @cmungall on https://github.com/monarch-initiative/monarch-app/issues/866#issuecomment-174013444

**Comment by cmungall** [comment]
It appears we have the desired behavior on beta

https://beta.monarchinitiative.org/owlsim/compareAttributeSets?a=MP:0001399&&b=HP:0004325&b=HP:0009887&b=MP:0005332&b=MP:0003131&b=HP:0003112&b=MP:0001488

**Comment by jmcmurry** [comment]
Here's how it should look when completed; this was done for Hippo publications browser which is no longer; however the basic user design applies and worked well at the time.

<img src="https://user-images.githubusercontent.com/3658863/103584737-c1e4f280-4e96-11eb-8c04-f39f2825f370.png" width="500" />

Right now, there is no way to tweak anything other than the list of recognized phenotypes. If you could use color codes for the kinds of entities recognized, that would help as well.  Ideally, we should capture which recognized concepts the user validates as this can improve the algorithm, however, that is more of a long-range goal.

<img src="https://user-images.githubusercontent.com/3658863/103585201-839c0300-4e97-11eb-944e-cc4f6e63afc8.png" width="500" />

Any concepts which are recognized but not one of the above 5 types (or anatomy) should be ignored I think
