### ISSUE TITLE
autocomplete to gene with no organism identified

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#876]
I can autocomplete on a gene "SOX9" that looks human based on caps, but takes me to this page:
http://beta.monarchinitiative.org/gene/NCBIGene%3A396840
it says here that the organism is not specified.
turns out this is Sus scrofa (pig), but you don't know this on the Monarch page nor in autocomplete.
Since we have no data showing for pig on this gene page right now, perhaps we should hide these genes from autocomplete/page rendering?

**Comment by pnrobinson** [comment]
It seems that this page:
http://beta.monarchinitiative.org/search/Sox9
should be shown if someone enteres Sox9 (whatever capitalization), and that this page should provide some more details about the species (several of which are represented). Probably something for the next release and sorry if this has been mentioned before!
-Peter

**Comment by mellybelly** [comment]
Agreed- and that landing page should show the species latin and common names

**Comment by cmungall** [comment]
- Species labels on autocomplete and search: #851 high priority
- Gene pages: We only fully load some species into SciGraph/Golr
  - Human looks fine: http://beta.monarchinitiative.org/gene/NCBIGene:6662
  - Pig does not http://beta.monarchinitiative.org/gene/NCBIGene%3A396840

Yes, we should be consistent and only show X in search if we have complete information on X. I assume for pig we load panther homology but not other sources (still odd how homology table is blank).

I tagged this with the data label, which means if we want this fixed in FOL then we push back FOL two weeks.

**Comment by kshefchek** [comment]
In regards to adding taxon to vocab services (autocomplete and search), if I understand correctly we will need to add this as a node property, will chat with @ccondit about this tomorrow.

**Comment by nlwashington** [comment]
Note that Pig has taxons on duckworth:
http://duckworth.crbs.ucsd.edu:9000/scigraph/graph/neighbors/NCBIGene:396840?depth=1&blankNodes=false&relationshipType=RO_0002162&direction=BOTH&project=%2A

**Comment by kshefchek** [comment]
We're pulling the taxon from SciGraph; however, we have a portion of the code that hardcodes the conversion of NCBI taxons to latin name (terrible I know).  Will update for additional species, but will also think about a more robust solution.
