### ISSUE TITLE
cell lines should show up in models for BRCA1

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#878]
When i go here:
http://beta.monarchinitiative.org/gene/NCBIGene:672

none of the cell lines show up on the models tab.

but we know that the genotypes of many of the cell lines have variations in BRCA1 (as evidenced by the multitude of genotypes in the genotype tab:
BRCA1(ARG1443TER) [GM14637]

this may be a missing pattern in our scigraph.  @ccondit we should check, and @kshefchek needs to make sure that it is populating the golr right.

**Comment by kshefchek** [comment]
I can't track it down in the unfiltered view, I'll take a look at the cypher to see if we need to make some tweaks.

**Comment by kshefchek** [comment]
Something like this should work, but with less specific terms than sequence-variant locus and is_allele_of

```
    (someEntity)<-[is_model_for:RO_0003301]-(subject:model)-[:RO_0001000|GENO_0000222*1..2]->(genotype:genotype)-[:GENO_0000382]->(variant:GENO_0000002)-[:GENO_0000408] ->(object:gene)
```

Will test locally.

**Comment by kshefchek** [comment]
In the example above I think I have the orientation of the anonymous node (foaf:person in this example) and the variant is wrong.  I believe we link a variant to this anonymous node rather than the model directly.  I think this is why we're not seeing variants on model pages (for example: http://beta.monarchinitiative.org/model/Coriell:GM13705) which is linked to a variant in the turtle files.

**Comment by kshefchek** [comment]
After some testing there are two issues with the current query:
- There is no (anon)<-[:RO_0003301]-(model) relationship
- The model is linked to a gene via an anonymous variant linked to an OMIM variant.  Right now the query only traverses one node.

In Coriell we link anonymous variants to variants using GENO_0000382, for example:
(_:113705.0006)-[GENO_0000382]->(OMIM_113705.0006)

Is this correct or should this be a sameAs relationship?

I've updated the query in the config file so that this data will be captured, see https://github.com/monarch-initiative/configs/commit/e756d7b51ceb608981ed17f3b1a2616fed768c7b

@nlwashington could you review?  I'm not sure if making the :RO_0003301 relationship optional will cause the query to bring in non-model data.  I'm testing this now,

**Comment by kshefchek** [comment]
Updated with https://github.com/monarch-initiative/configs/commit/58d2fb306b4f7052be088731a66981bf46bdd845

I'm instead using a UNION query with the relationship:

```
    (model)-[:RO_0001000]->(anonPerson)-[GENO_0000222]->(genotype)...
```

But we could get even more specific with something like:

```
    (CLO_0000031)-[:type]-(model)-[:RO_0001000]->(anonPerson)-[GENO_0000222]->(genotype)...
```

**Comment by kshefchek** [comment]
@mbrush confirmed the modelling is correct (see https://github.com/monarch-initiative/monarch-app/issues/878#issuecomment-129502088).  Will close after the next GOlr reload.

**Comment by jmcmurry** [comment]
@kshefchek, models tab of http://beta.monarchinitiative.org/gene/NCBIGene:672 is still blank, so I'm assuming we're still waiting on the new release?

**Comment by kshefchek** [comment]
See https://github.com/monarch-initiative/configs/commit/827e891adebcd6dbe845265a69a3dd892ebf44ae

**Comment by kshefchek** [comment]
This is fixed see http://stage.monarchinitiative.org/gene/NCBIGene:672

**Comment by nlwashington** [comment]
we're getting lots of duplicates on this page; do we know why?
