### ISSUE TITLE
Make disease the first tab in phenotype page

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#88]
E.g.
http://tartini.crbs.ucsd.edu/phenotype/HP_0007033

Disease tab should be first

**Comment by harryhoch** [comment]
currently the tabs are overview, disease,genotype. Similarity was last, but it was removed as per https://github.com/monarch-initiative/monarch-app/issues/71. 

Do you want disease before overview? I'm not sure I like that idea, as it raises consistency issues. Keeping "overview" first seems safer

**Comment by sarahjkim** [comment]
In light of #70, I think we should revert Overview to the initial tab. This is because some diseases do not have phenotypes, and because I am greying those tabs out, the first thing the user will see will be an empty tab. Overview, however, will always exist because there are always synonyms/IDs to display.
