### ISSUE TITLE
Add back species facets

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#899]
We want species facets for the Sept deadline. This would be for phenotype pages only.

The facets could be back en masse, and made user friendlier (todo: link this ticket to previous tickets), or this could be broken out.

One possibility is for species facet to be an icon with a picture of the mouse/human/fish etc. Obviously this doesn't scale to arbitrary species, so we would have human, the main models, and then something for "other vertebrate" or "generic vertebrate" etc

Indicators of annotation counts also useful.

**Comment by jmcmurry** [comment]
I'm adding the vestigial tag to prompt clarification on whether there's been any progress on similar tickets that could be leveraged here. Species facets were brought back somehwere; where was this? I'm losing track. @kshefchek

**Comment by DoctorBud** [comment]
I'm not sure which species facets you are referring to, but I recently cleaned up the species filtering in the phenotype pages. I don't know if there was a ticket, I just recall Nicole saying they looked bad, so I fixed them. They may have been disabled around the time this ticket was created.

Here's a Screenshot of production:

<img width="752" alt="a" src="https://cloud.githubusercontent.com/assets/2450553/11860173/d21bb97e-a426-11e5-93c0-b8492f3edf22.png">

**Comment by jmcmurry** [comment]
Thanks @DoctorBud, looks much better also on mac / chrome which was the most problematic environment.
- [x] Please comment out the top filter box if possible as we are not including multiple groups of filters at this time anyway. 
- [ ] Longer-term, the group had at one point discussed doing away with the bbop widget altogether in favor of a more customized solution. Proposed design below for discussion; it doesn't need to be done right now or in this exact way.
  - [x] Make the filter a dropdown instead
  - [x] Utilize checkboxes

<img width="912" alt="screen shot 2015-12-16 at 11 04 04 pm" src="https://cloud.githubusercontent.com/assets/3658863/11863529/6a56231a-a449-11e5-9d20-18a3d232b310.png">

Pros: 
- more compact representation leaves more room for actual results
- the +/- filters do work but are not an industry standard; the above is more closely aligned with the kind of "select all" "select none" behavior users would probably expect. 
- Each result is specific to one species only; thus the use case (for species) doesn't require the "must / may / must not" nuance that (I think?) the +/- filters are designed to address. 

@ Team, thoughts welcome. Please +1 if you agree, propose an alternative or raise a concern. thanks :)

ps I think that the order of the species in the filter menu is still the best done by nuber of hits (eg. rather than grouping by taxonomic relatedness). If we start getting way 20+ species represented in a single set of results, we will need to think about grouping them more meaningfully.

**Comment by cmungall** [comment]
+1

**Comment by mellybelly** [comment]
I'd also love a more taxonomic selector-  one that could subdivide the choices based on larger taxonomic groups. eg. amniotes, vertebrata, rodentia, etc. and also include common taxonomic names for non-experts.

**Comment by cmungall** [comment]
larger taxonomic groups can be handled with a model selector analogous to https://github.com/geneontology/amigo/issues/247

**Comment by jmcmurry** [comment]
Taxonomic groups are addressed in a different ticket https://github.com/monarch-initiative/monarch-app/issues/1126
