### ISSUE TITLE
Dove graphs – fix display when expanding phenotype class below the break 

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/monarch-legacy#917]
If I click on a phenotype at the bottom of a long list to expand its subclasses, when the new page opens with the expanded subclasses it doesn't scroll back up to the top of the window, so I am left looking at the Disease association graph and have to manually scroll up to see my unfolded subclasses.

Recreate:  From Explore Genes (http://beta.monarchinitiative.org/gene), navigate to Nervous system > Nervous System Morphology.  Scroll down and click the Morphology Cornea phenotype.  A new window opens with the subclass(es) of this class displayed, but I have to scroll up to see it.  Not a huge deal, but a bit confusing for the user.

**Comment by jmcmurry** [comment]
1. Morphology Cornea phenotype seems no longer to be listed Nervous System Morphology. Maybe this is intended; not sure. @mbrush ?
2. In a long list of phenotypes, if there are no subtypes it is impossible to tell, because the warning message occurs outside of the visible frame (in the legend). So clicking on a leaf node does nothing and shows nothing, unless you know where to look. Even when the list isn't this long, that behaviour has been a quick fix that needs a longer term solution. @DoctorBud perhaps you can help with this? I'm provisionally including in Thanksgiving release in case there's an easy fix.
   ![screen shot 2015-10-13 at 21 34 53](https://cloud.githubusercontent.com/assets/3658863/10474962/4d70405c-71f2-11e5-8071-939f72f8c8ee.png)

**Comment by jmcmurry** [comment]
Related to https://github.com/monarch-initiative/monarch-app/issues/915
