### ISSUE TITLE
landing pages with/out slash

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#985]
i notice on beta that i can get to

http://beta.monarchinitiative.org/phenotype

but not to

http://beta.monarchinitiative.org/phenotype/

maybe this isn't a problem, but something i notice.   @doctorbud?

**Comment by cmungall** [comment]
webapp has

```
web.wrapRouteGet(app, '/phenotype', '/phenotype', [], phenotypeLandingHandler, errorResponse);
```

I guess we have to add another explicitly...?

**Comment by DoctorBud** [comment]
Yeah. It's a known bug, but I didn't think anyone would care. Chris is correct  that I should add a separate route to handle it (it'll be a one-line fix, since I've extracted the handlers into separate named functions for almost all routes).

I'll fix it. I might be able to take advantage of my webenv.wrapRouteXXX() code so that the extra route gets added automatically. Yeah, that's what I will do.

**Comment by DoctorBud** [comment]
I think I fixed it.
